### PR TITLE
Reduce number of git checkouts using stash/unstash

### PR DESCRIPTION
**Pull request by thbkrkr**
This commit reduces the number of `git clone` in the jobs that run parallel stages in remote workers.
The default automatic checkout is disabled in favor of an unique checkout + stash of the source code. Then the source code is unstashed in each step run in parallel in the remote workers.

We recently added a retry to the checkout to help with some checkout/github connection failures. This is a small optimization than is nice to also have to help with this and which is quite cheap.

I'm not completely sure we want this. Let me know what you think.

Relates to #3066.

### CODE REVIEW

**Comment by thbkrkr** [comment]
> Very nice!  Do you think this would work for the PR job as well? I tried to do it once but it didn't work for some reason that I can't remember now.

I think so, I will have a look. I was focused on the E2E jobs.

**Comment by thbkrkr** [comment]
I simplified the pr job in 673d72d by removing the remote execution of the stage `Run smoke E2E tests` (by removing the agent) which is not necessary and by removing all the extra checkouts because the default checkout is enough.

**Comment by thbkrkr** [comment]
jenkins test this please

**Comment by thbkrkr** [comment]
jenkins test this please

**Comment by thbkrkr** [comment]
jenkins test this please

**Comment by thbkrkr** [comment]
jenkins test this please

**Comment by anyasabo** [comment]
Maybe related to https://github.com/elastic/cloud-on-k8s/issues/3173 it looks like this is failing because some license tests are flaky, hard to imagine this change caused them

>10:33:14  === [31mFAIL[0m: pkg/controller/common/license TestChecker_EnterpriseFeaturesEnabled/valid_trial:_OK (0.01s)
10:33:14      TestChecker_EnterpriseFeaturesEnabled/valid_trial:_OK: check_test.go:131: Checker.EnterpriseFeaturesEnabled() = false, want true
10:33:14      --- FAIL: TestChecker_EnterpriseFeaturesEnabled/valid_trial:_OK (0.01s)
10:33:14  
10:33:14  === [31mFAIL[0m: pkg/controller/common/license TestChecker_EnterpriseFeaturesEnabled/valid_legacy_trial:_OK (0.00s)
10:33:14      TestChecker_EnterpriseFeaturesEnabled/valid_legacy_trial:_OK: check_test.go:131: Checker.EnterpriseFeaturesEnabled() = false, want true
10:33:14      --- FAIL: TestChecker_EnterpriseFeaturesEnabled/valid_legacy_trial:_OK (0.00s)
10:33:14  
10:33:14  === [31mFAIL[0m: pkg/controller/common/license TestChecker_EnterpriseFeaturesEnabled (1.66s)
10:33:14  
10:33:14  === [31mFAIL[0m: pkg/controller/common/license Test_CurrentEnterpriseLicense/get_valid_trial_enterprise_license:_OK (0.00s)
10:33:14      Test_CurrentEnterpriseLicense/get_valid_trial_enterprise_license:_OK: check_test.go:234: Checker.CurrentEnterpriseLicense() = <nil>, want true
10:33:14      --- FAIL: Test_CurrentEnterpriseLicense/get_valid_trial_enterprise_license:_OK (0.00s)
10:33:14  
10:33:14  === [31mFAIL[0m: pkg/controller/common/license Test_CurrentEnterpriseLicense (1.75s)
10:33:14  
10:33:14  === [31mFAIL[0m: pkg/license Test_Start (11.64s)
10:33:14      Test_Start: reporter_test.go:266: 
10:33:14          	Error Trace:	reporter_test.go:266
10:33:14          	Error:      	Condition never satisfied
10:33:14          	Test:       	Test_Start
10:33:14  
10:33:14

**Comment by anyasabo** [comment]
jenkins test this please

**Comment by thbkrkr** [comment]
jenkins test this please

**Comment by thbkrkr** [comment]
jenkins test this please

**Comment by thbkrkr** [comment]
jenkins test this please

**Comment by thbkrkr** [comment]
This is pretty interesting. The non-use of an agent (https://github.com/elastic/cloud-on-k8s/pull/3115/commits/68d7990c12eccf4d98c9e9fea16677ab3a8cf7aa) when executing the unit tests and the e2e SmokeTest reveals a race condition in the license unit tests. 

It is reproducible in local:
```> go test ./pkg/license  -race
--- FAIL: Test_Start (11.28s)
    reporter_test.go:266: 
                Error Trace:    reporter_test.go:266
                Error:          Condition never satisfied
                Test:           Test_Start
FAIL
FAIL    github.com/elastic/cloud-on-k8s/pkg/license     11.448s
FAIL
```

The issue is in `publicKeyFor` where we return the data of the secret and we get the secret at the same time:
https://github.com/elastic/cloud-on-k8s/blob/e5b63347c25117e27b2a43100ec6a2e7f6e7562a/pkg/controller/common/license/check.go#L43-L47

**Comment by thbkrkr** [comment]
It is a small bug but I finally thought it was better to treat it in a dedicated issue. So, I will wait to have it in master and merge master in this PR.

**Pull request merged**
