### PR TITLE
Fix nightly release job

### PR DESCRIPTION
**Pull request by artemnikitin**
PR https://github.com/elastic/cloud-on-k8s/pull/1806 brokes nightly build by adding `ci-check` make target to it. As part of `ci-check` executed `check-local-changes` which check for uncommitted changes. It fails for release build on CI because in the process of release some temporary txt files created.

### CODE REVIEW

**Comment by charith-elastic** [comment]
Wouldn't it be better to add `eck_image.txt` to `.gitignore` instead? I am a bit wary of disabling checks selectively. I realise that PR and E2E runs should catch any problems long before the nightly run but it feels better to keep all builds as uniform as possible.

**Comment by artemnikitin** [comment]
@charith-elastic done!

**Comment by artemnikitin** [comment]
jenkins test this please

**Comment by artemnikitin** [comment]
jenkins test this please 😢

**Pull request merged**
