### PR TITLE
Remove extra white space in Dockerfile

### PR DESCRIPTION
**Pull request by jiuker**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/cloud-on-k8s/tree/main/CONTRIBUTING.md)?
- If you submit code, is your pull request against main? We recommend pull requests against main. We will backport them as needed.
should remove this one space？
if not ,it will run error!

### CODE REVIEW

**Comment by jiuker** [comment]
> > > Thanks.
> > > Jenkins test this please.
> > > Can you please sign the CLA? https://www.elastic.co/contributor-agreement
> > 
> > 
> > yes , I have signed
> 
> Sorry, that doesn't seem to be the case, could you try again?

How about now?

**Comment by thbkrkr** [comment]
I see you but it doesn't work. I think the problem is that the email you used to sign the CLA doesn't match the email you used to commit.

**Comment by thbkrkr** [comment]
The email you used to sign the CLA still doesn't match the email you used to commit. Check the commit detail (`git log -1`): `...@daocloud.io` != `...@qq.com`.

**Comment by jiuker** [comment]
> The email you used to sign the CLA still doesn't match the email you used to commit. Check the commit detail (`git log -1`): `...@daocloud.io` != `...@qq.com`.

sorry,i signed agained!I forgot!try it again plz!

**Comment by thbkrkr** [comment]
Jenkins test this please.

**Review by thbkrkr — APPROVED** [review]

**Pull request merged**
