### PR TITLE
Bump Stack version to 8.8.0 / 8.9.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by barkbay**
Bump Stack version to 8.8.0 / 8.9.0-SNAPSHOT in samples, recipes and e2e tests.

### CODE REVIEW

**Review by thbkrkr — APPROVED** [review]

**Comment by barkbay** [comment]
buildkite test this -f p=kind -m s=8.8.0,s=8.9.0-SNAPSHOT

**Comment by barkbay** [comment]
`TestFleetCustomLogsIntegrationRecipe/ES_data_should_pass_validations` failed on both `8.8.0` and `8.9.0-SNAPSHOT`

### 8.8.0

```json
{
	"Time": "2023-05-30T12:08:57.212461431Z",
	"Action": "output",
	"Package": "github.com/elastic/cloud-on-k8s/v2/test/e2e/agent",
	"Test": "TestFleetCustomLogsIntegrationRecipe/ES_data_should_pass_validations",
	"Output": "        \t            \telasticsearch client failed for https://elasticsearch-ktzm-es-internal-http.e2e-5qk1r-mercury.svc:9200/_data_stream/logs-generic-default: 404 Not Found: {Status:404 Error:{CausedBy:{Reason: Type:} Reason:no such index [logs-generic-default] Type:index_not_found_exception StackTrace: RootCause:[{Reason:no such index [logs-generic-default] Type:index_not_found_exception}]}}\n"
}
```

Note that we have a permission error while deleting some resources once the test has failed:

```json
{
	"Time": "2023-05-30T12:08:57.222063726Z",
	"Action": "output",
	"Package": "github.com/elastic/cloud-on-k8s/v2/test/e2e/agent",
	"Test": "TestFleetCustomLogsIntegrationRecipe/ES_data_should_pass_validations",
	"Output": "{\"error\":\"kibanas.kibana.k8s.elastic.co is forbidden: User \\\"system:serviceaccount:e2e-5qk1r-system:e2e-5qk1r\\\" cannot deletecollection resource \\\"kibanas\\\" in API group \\\"kibana.k8s.elastic.co\\\" in the namespace \\\"e2e-5qk1r-system\\\"\",\"error.stack_trace\":\"github.com/elastic/cloud-on-k8s/v2/test/e2e/test.StepList.RunSequential\\n\\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/step.go:61\\ngithub.com/elastic/cloud-on-k8s/v2/test/e2e/test/helper.RunFile\\n\\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/helper/yaml.go:169\\ngithub.com/elastic/cloud-on-k8s/v2/test/e2e/agent.runAgentRecipe\\n\\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/agent/recipes_test.go:239\\ngithub.com/elastic/cloud-on-k8s/v2/test/e2e/agent.TestFleetCustomLogsIntegrationRecipe\\n\\t/go/src/github.com/elastic/cloud-on-k8s/t"
}
```

### 8.9.0-SNAPSHOT

Same error:

```json
{
	"Time": "2023-05-30T12:13:03.543406803Z",
	"Action": "output",
	"Package": "github.com/elastic/cloud-on-k8s/v2/test/e2e/agent",
	"Test": "TestFleetCustomLogsIntegrationRecipe/ES_data_should_pass_validations",
	"Output": "        \t            \telasticsearch client failed for https://elasticsearch-l5s4-es-internal-http.e2e-cyzbf-mercury.svc:9200/_data_stream/logs-generic-default: 404 Not Found: {Status:404 Error:{CausedBy:{Reason: Type:} Reason:no such index [logs-generic-default] Type:index_not_found_exception StackTrace: RootCause:[{Reason:no such index [logs-generic-default] Type:index_not_found_exception}]}}\n"
}
```

Might be similar to https://github.com/elastic/cloud-on-k8s/issues/5355? (I did not check yet)

**Comment by barkbay** [comment]
Additional comments:

* `TestFleetCustomLogsIntegrationRecipe` was ✅ during the run of the e2e pipeline for `v2.8.0-bc7` on `8.8.0-SNAPSHOT`

```json
{
	"Time": "2023-05-24T12:58:52.015538733Z",
	"Action": "pass",
	"Package": "github.com/elastic/cloud-on-k8s/v2/test/e2e/agent",
	"Test": "TestFleetCustomLogsIntegrationRecipe",
	"Elapsed": 374.01
}
```

* Log input is deprecated

```json
{
	"log.level": "warn",
	"@timestamp": "2023-05-30T11:39:44.818Z",
	"message": "DEPRECATED: Log input. Use Filestream input instead.",
	"component": {
		"binary": "filebeat",
		"dataset": "elastic_agent.filebeat",
		"id": "log-default",
		"type": "log"
	},
	"log": {
		"source": "log-default"
	},
	"log.logger": "cfgwarn",
	"log.origin": {
		"file.line": 90,
		"file.name": "log/input.go"
	},
	"service.name": "filebeat",
	"ecs.version": "1.6.0",
	"ecs.version": "1.6.0"
}
```

**Comment by barkbay** [comment]
Found this error logged at the warning level in Kibana logs:

```
[2023-05-30T11:38:37.209+00:00][WARN ][plugins.fleet] PackagePolicyValidationError:
Package policy is invalid: inputs.logfile.streams.log.logs.vars.paths:
Log file path is required
inputs.logfile.streams.log.logs.vars.data_stream.dataset: Dataset name is required
    at validatePackagePolicyOrThrow (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/package_policy.js:1197:13)
    at preconfigurePackageInputs (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/package_policy.js:1584:3)
    at /usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/preconfiguration.js:282:212
    at addPackageToAgentPolicy (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/agent_policy.js:776:53)
    at addPreconfiguredPolicyPackages (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/preconfiguration.js:282:53)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ensurePreconfiguredPackagesAndPolicies (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/preconfiguration.js:219:7)
    at createSetupSideEffects (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/setup.js:86:7)
    at awaitIfPending (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/setup_utils.js:35:20)
    at /usr/share/kibana/node_modules/@kbn/fleet-plugin/server/plugin.js:285:9
```

Which may match the custom policy in this:

```yaml
    - name: Elastic Agent on ECK policy
      id: eck-agent
      namespace: default
      monitoring_enabled:
      - logs
      - metrics
      unenroll_timeout: 900
      package_policies:
      - name: system-1
        id: system-1
        package:
          name: system
      - package:
          name: log
        name: log-1
        inputs:
        - type: logfile
          enabled: true
          streams:
          - data_stream:
              dataset: log.log
            enabled: true
            vars:
            - name: paths
              value:
              - '/var/log/containers/*${kubernetes.container.id}.log'
            - name: custom
              value: |
                symlinks: true
                condition: ${kubernetes.namespace} == 'default'
```

**Comment by barkbay** [comment]
Reopening https://github.com/elastic/cloud-on-k8s/issues/5105#issuecomment-1569668693, I'll skip this test in the meantime.

**Comment by thbkrkr** [comment]
@barkbay did we miss backporting this or is it delayed due to #5105?

**Comment by barkbay** [comment]
> @barkbay did we miss backporting this or is it delayed due to https://github.com/elastic/cloud-on-k8s/issues/5105?

I did not realize that it should be backported tbh 🤔.  I had a look at [the `2.7` branch, it is also still referring to `8.6.1`](https://github.com/elastic/cloud-on-k8s/blob/v2.7.0/config/samples/apm/apm_es_kibana.yaml) while it was released with `8.7.0`. Should we backport this PR for every release?

**Comment by thbkrkr** [comment]
It is the `v2.8.0` label that misled me.

> Should we backport this PR for every release?

In my mind (IDK why) it was something we did, but in reality it is a mess, we are not consistent and we have only done it 3 times. 
```sh
1.4 -> 7.9.2  
1.5 -> 7.11.0 
1.6 -> 7.12.0 
1.7 -> 7.14.0 🟢 #4733 pebrc / r.m.: barkbay
1.8 -> 7.14.0  
1.9 -> 7.15.0 
2.0 -> 7.16.2 
2.1 -> 8.0.0   
2.2 -> 8.2.0 🟢 #5655 pebrc / r.m.: thb/naemono
2.3 -> 8.2.0   
2.4 -> 8.4.2 🟢 #6034 thb / r.m.: davidk
2.5 -> 8.4.2  
2.6 -> 8.5.0
2.7 -> 8.6.1
2.8 -> 8.7.0
```

Note that you approved the last two :) (#5655, #6034).

**Pull request merged**
