### PR TITLE
[E2E] Increase Agent memory

### PR DESCRIPTION
**Pull request by barkbay**
It seems that https://github.com/elastic/cloud-on-k8s/pull/7884 was not enough.

### CODE REVIEW

**Comment by barkbay** [comment]
✅  `TestFleetMode` on OCP

**Comment by barkbay** [comment]
buildkite test this -f p=aks,TESTS_MATCH=TestMultiOutputRecipe

**Comment by barkbay** [comment]
buildkite test this -f t=TestMultiOutputRecipe -m p=aks

**Comment by barkbay** [comment]
Still failing on AKS:

```json
{
    "Time": "2024-06-12T11:56:07.577331197Z",
    "Action": "output",
    "Package": "github.com/elastic/cloud-on-k8s/v2/test/e2e/agent",
    "Test": "TestMultiOutputRecipe/ES_data_should_pass_validations",
    "Output": "elasticsearch client failed for https://...:9200/_data_stream/logs-elastic_agent-default: 404 Not Found: {Status:404 Error:{CausedBy:{Reason: Type:} Reason:no such index [logs-elastic_agent-default] Type:index_not_found_exception StackTrace: RootCause:[{Reason:no such index [logs-elastic_agent-default] Type:index_not_found_exception}]}}\n"
}
```

**Comment by barkbay** [comment]
buildkite test this -f t=TestMultiOutputRecipe -m p=aks

**Review by thbkrkr — APPROVED** [review]

**Pull request merged**
