### PR TITLE
use core-ubuntu-2004 image for gcp steps

### PR DESCRIPTION
**Pull request by jonahbull**
The `elastic-buildkite-agent-ubuntu-2004-lts` image was one of the very first hand-rolled images that we created when experimenting with Buildkite and hasn't been updated/improved in quite some time. One of its shortcomings is that it still has a filebeat/metricbeat configuration that sends PagerDuty alerts when the VM's root volume goes over 90% full, which causes unnecessary toil for our SRE colleagues.

Switch over to the newer, actively maintained `core-ubuntu-2004` image, which is built automatically every day and should provide the same functionality as the previous image but without the PagerDuty alerts.

### CODE REVIEW

**Comment by jonahbull** [comment]
Hm, interesting. As I'd expect the version from `core-ubuntu-2004` is much newer.

`core-ubuntu-2004`: 
```
$ docker version
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:12 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:12 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

`elastic-buildkite-agent-ubuntu-2004-lts`:
```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by thbkrkr** [comment]
```
# core-ubuntu-2004
runc:
  Version:          1.1.9
```

> KIND v0.20.0 fixes runc 1.1.6+

https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0

We are using kind 0.19.0 since #7129.

Could you test the v0.20.0 (kindest/node also need to be updated using the sha256 of the corresponding kind version listed in the release note) or could I update your branch?

**Comment by jonahbull** [comment]
@thbkrkr I _think_ I made the right set of changes to use `0.20.0`, feel free to make any changes you need to the branch though.

**Comment by thbkrkr** [comment]
> @thbkrkr I think I made the right set of changes to use 0.20.0

Yes, LGTM. We are making progress. Now it is the version of Docker installed in the buildkite agent that we also need to update. This is a bit twisted, even though for kind clusters we use a gcp bk agent, we still run all commands from a Docker container created using the same image as the bk agent used to create other flavors of k8s clusters.

**Review by thbkrkr — APPROVED** [review]

**Pull request merged**
