### PR TITLE
Do not prepopulate file-based settings with empty objects

### PR DESCRIPTION
**Pull request by pebrc**
A operator `settings.json` even with empty settings for each supported setting requires the appropriate handlers in Elasticsearch to be loaded. 

```
{
  "metadata": {
    "version": "1728032913938346943",
    "compatibility": "8.6.1"
  },
  "state": {
    "cluster_settings": {},
    "snapshot_repositories": {},
    "slm": {},
    "role_mappings": {},
    "ilm": {},
    "ingest_pipelines": {},
    "index_templates": {
      "component_templates": {},
      "composable_index_templates": {}
    }
  }
}
```

This causes problems when Elasticsearch is configured in a way that certain handlers are not available. In https://github.com/elastic/cloud-on-k8s/issues/8042 a user was running with `xpack.security.enabled: false` which meant that the security related handlers for role mappings were not available and the cluster never became ready. 

While we do not support running with security disabled in ECK it still seems appropriate to orchestrate ES in such a way that this problem is avoided. This PR suggests to move the following default file instead: 

```
{
  "metadata": {
    "version": "1728032913938346943",
    "compatibility": "8.6.1"
  },
  "state": {}
}
```

### CODE REVIEW

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,t=TestStackConfigPolicy -m s=8.14.3,s=8.15.1,s=8.16.0-SNAPSHOT

**Review by thbkrkr — DISMISSED** [review]

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,t=TestStackConfigPolicy -m s=8.14.3,s=8.15.1,s=8.16.0-SNAPSHOT

**Comment by pebrc** [comment]
There seems to be an issue with an empty settings file in that it does not correctly delete the snapshot repos created via file-based settings. 

Just consider the failing e2e test: 
1.  ES cluster with a snapshot repo installed through SCP
```
k8surl GET  _snapshot
{"repo_test":{"type":"gcs","settings":{"bucket":"my-bucket","base_path":"snapshots/default-elasticsearch-sample"}}}⏎  
```
2. Delete SCP
3. Settings file is emtpy:
```
kubectl exec elasticsearch-sample-es-default-0 -- cat config/operator/settings.json | jq
Defaulted container "elasticsearch" out of: elasticsearch, elastic-internal-init-filesystem (init), elastic-internal-suspend (init)
{
  "metadata": {
    "version": "1728897840507149000",
    "compatibility": "8.6.1"
  },
  "state": {}
}
```
5. Snapshot repo remains configured in the ES custer
```
k8surl GET  _snapshot
{"repo_test":{"type":"gcs","settings":{"bucket":"my-bucket","base_path":"snapshots/default-elasticsearch-sample"}}}⏎  
```

**Comment by pebrc** [comment]
I am closing this for the time being we can reconsider when the issue with snapshots is fixed

**Pull request closed without merging**
