### PR TITLE
Update stack versions after 8.11 stack release

### PR DESCRIPTION
**Pull request by rhr323**
This PR updates the stack versions tested to 8.11.1 and 8.12.0-SNAPSHOT.

### CODE REVIEW

**Review by thbkrkr — COMMENTED** [review]
Nit: `s/8.11.0/8.11.1/` in `hack/upgrade-test-harness`.
```sh
> grep '8\.11\.0' -r hack
hack/upgrade-test-harness/testdata/v2100/stack.yaml:  version: 8.11.0
hack/upgrade-test-harness/testdata/v2100/stack.yaml:  version: 8.11.0
hack/upgrade-test-harness/testdata/v2100/stack.yaml:  version: 8.11.0
hack/upgrade-test-harness/testdata/v2100/stack.yaml:  version: 8.11.0
hack/upgrade-test-harness/testdata/v2100/stack.yaml:  version: 8.11.0
hack/upgrade-test-harness/testdata/v2100/stack.yaml:  version: 8.11.0
hack/upgrade-test-harness/conf.yaml:    stackVersion: 8.11.0
```
```sh
while read f; do \
    sed -i.bak -E "s|8\.11\.0|8.11.1|g" "$f"; rm "$f.bak"; \
done < <(find hack/upgrade-test-harness -name "*.yaml")
```

I noticed that we missed bumping the version of eck-stack Helm charts in #7241. Maybe fix this in this PR?
```sh
while read f; do \
    sed -i.bak -E "s|0\.8\.0-SNAPSHOT|0.9.0-SNAPSHOT|g" "$f"; rm "$f.bak"; \
done < <(find deploy/eck-stack -name Chart.yaml)
```

**Comment by rhr323** [comment]
Thanks @thbkrkr , I applied the changes you recommended.

I also found more 8.11.0, which I guess we should also update: https://github.com/elastic/cloud-on-k8s/pull/7327/commits/406489e3169e54dc0a24abcec094051d597eeeda (let me know if not 😉 )

**Comment by thbkrkr** [comment]
> I also found more 8.11.0, which I guess we should also update: https://github.com/elastic/cloud-on-k8s/commit/406489e3169e54dc0a24abcec094051d597eeeda (let me know if not 😉 )

We can but it doesn't matter, it's just for testing that if we set x.y.z, we get x.y.z. 

I missed that we also need to update the examples, not only `Chart.yaml`, so:
```sh
while read f; do \
    sed -i.bak -E "s|0\.8\.0-SNAPSHOT|0.9.0-SNAPSHOT|g" "$f"; rm "$f.bak"; \
done < <(find deploy/eck-stack -name Chart.yaml)
```

**Review by thbkrkr — APPROVED** [review]

**Comment by rhr323** [comment]
buildkite test this -f p=kind -m s=8.11.1,s=8.12.0-SNAPSHOT

**Comment by rhr323** [comment]
buildkite test this -f p=kind -m s=8.11.1,s=8.12.0-SNAPSHOT

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke -m s=8.11.1,s=8.12.0-SNAPSHOT

**Comment by rhr323** [comment]
buildkite test this -f p=gke -m s=8.11.1,s=8.12.0-SNAPSHOT

**Comment by thbkrkr** [comment]
`TestMetricbeatStackMonitoringRecipe` failed because of #7322, reverted in #7328.

**Comment by rhr323** [comment]
buildkite test this -f p=gke -m s=8.11.1,s=8.12.0-SNAPSHOT

**Pull request merged**
