### PR TITLE
Moving gke used for ci from europe to us

### PR DESCRIPTION
**Pull request by thbkrkr**
🇺🇸   ... ◀️   ...  🐳  ⛵ 🐟   ...  ◀️   ... 🇪🇺

### CODE REVIEW

**Comment by thbkrkr** [comment]
buildkite test this -p t=TestSmoke -f 
s=6.8.23,s=7.16.3,s=7.17.8,s=8.0.1,s=8.1.3,s=8.2.3,s=8.3.3,s=8.4.3,s=8.5.3,s=8.6.2,s=8.7.1,s=8.8.0,s=8.8.0^E2E_DEPLOY_CHAOS_JOB=true,s=8.9.0-SNAPSHOT

**Comment by thbkrkr** [comment]
buildkite test this -p t=TestSmoke -f s=6.8.23,s=7.16.3,s=7.17.8,s=8.0.1,s=8.1.3,s=8.2.3,s=8.3.3,s=8.4.3,s=8.5.3,s=8.6.2,s=8.7.1,s=8.8.0,s=8.8.0^E2E_DEPLOY_CHAOS_JOB=true,s=8.9.0-SNAPSHOT

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,t=TestSmoke -m s=6.8.23,s=7.16.3,s=7.17.8,s=8.0.1,s=8.1.3,s=8.2.3,s=8.3.3,s=8.4.3,s=8.5.3,s=8.6.2,s=8.7.1,s=8.8.0,s=8.8.0^E2E_DEPLOY_CHAOS_JOB=true,s=8.9.0-SNAPSHOT

**Comment by thbkrkr** [comment]
There were no problems creating 15 GKE clusters in // as the daily e2e test pipeline does.

**Review by barkbay — APPROVED** [review]
LGTM 👍 

Let's try it 🤞

**Pull request merged**
