### PR TITLE
Make autopilot e2e test run on 1.26

### LINKED ISSUE #7751: GKE Autopilot tests broken on GKE 1.26
Since https://github.com/elastic/cloud-on-k8s/pull/7743 e2e cannot run on GKE Autopilot anymore.  Because we cannot go back to 1.25 as it does not exist anymore there is no quick fix. 

```
Failed to run e2e tests","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","error":"test run failed: unexpected status Failed for pod eck-e2e-l8u3b-n47kn","errorVerbose":"unexpected status Failed for pod eck-e2e-l8u3b-n47kn\
```

The underlying issue seems to be that GKE Autopilot has a mutating webhook that enforces a `1Gi` ephemeral storage limit: 

```
                   "resources": {
                            "limits": {
                                "cpu": "500m",
                                "ephemeral-storage": "1Gi",
                                "memory": "2Gi"
                            },
                            "requests": {
                                "cpu": "500m",
                                "ephemeral-storage": "1Gi",
                                "memory": "2Gi"
                            }
                        },
```

```
{"reason":"Evicted","message":"Pod ephemeral local storage usage exceeds the total limit of containers 1Gi. ","kind":"Pod","name":"eck-e2e-l8u3b-n47kn","namespace":"e2e-l8u3b-system"}
```

We run with `backoffLimit: 0` so no further attempt is made to run the tests (which would fail anyway)

I have not figured out what the container is writing into the ephemeral storage yet.

### PR DESCRIPTION
**Pull request by pebrc**
Fixes #7751

### CODE REVIEW

**Comment by pebrc** [comment]
buildkite test this -f t=TestAutopilot,p=gke-autopilot

**Comment by pebrc** [comment]
buildkite test this -f t=TestAutopilot,p=gke-autopilot

**Comment by pebrc** [comment]
buildkite test this -f t=TestAutopilot,p=gke-autopilot

**Comment by pebrc** [comment]
buildkite test this -f t=TestAutopilot,p=gke-autopilot

**Comment by pebrc** [comment]
This seems to work. Let's see if keeping the go mod cache in the ephemeral storage speeds up the build.

**Comment by pebrc** [comment]
buildkite test this -f t=TestAutopilot,p=gke-autopilot

**Comment by pebrc** [comment]
With GOMODCACHE and GOCACHE in `/tmp` 41m 21s
With GOCACHE in `/tmp` Ran in 39m 39s

Let's do a last one with the original settings.

**Comment by pebrc** [comment]
buildkite test this -f t=TestAutopilot,p=gke-autopilot

**Review by kvalliyurnatt — APPROVED** [review]

**Pull request merged**
