### PR TITLE
Bump linter

### PR DESCRIPTION
**Pull request by anyasabo**
Breaking out https://github.com/elastic/cloud-on-k8s/pull/3865 into smaller chunks that are less painful to review

In the next PRs:
- Will re-enable some new linters that are useful (especially gci, gofumpt, and noctx)
- Clear out some of the current exclusions that are no longer valid
- Add comments explaining why we do not want certain linters enabled

I can do that in separate commits here if you think it's easier to review in one PR. The last one was just too intermingled for me to even want to do an interactive rebase on it.

### CODE REVIEW

**Comment by anyasabo** [comment]
run full pr build

**Comment by anyasabo** [comment]
I don't think this failure was me
```

13:16:48  Successfully tagged docker.elastic.co/eck-ci/eck-ci-tools:290d60ed
13:16:48  Push docker.elastic.co/eck-ci/eck-ci-tools:290d60ed...
13:16:48  denied: requested access to the resource is denied
13:16:48  Retry 1/5 exited 1, retrying in 1 seconds...
13:16:48  denied: requested access to the resource is denied
13:16:48  Retry 2/5 exited 1, retrying in 2 seconds...
13:16:48  denied: requested access to the resource is denied
13:16:48  Retry 3/5 exited 1, retrying in 4 seconds...
13:16:52  denied: requested access to the resource is denied
13:16:52  Retry 4/5 exited 1, retrying in 8 seconds...
13:17:00  denied: requested access to the resource is denied
13:17:00  Retry 5/5 exited 1, no more retries left.
13:17:00  The push refers to repository [docker.elastic.co/eck-ci/eck-ci-tools]
13:17:00  The push refers to repository [docker.elastic.co/eck-ci/eck-ci-tools]
13:17:00  The push refers to repository [docker.elastic.co/eck-ci/eck-ci-tools]
13:17:00  The push refers to repository [docker.elastic.co/eck-ci/eck-ci-tools]
13:17:00  The push refers to repository [docker.elastic.co/eck-ci/eck-ci-tools]
13:17:00  Makefile:63: recipe for target 'ci-build-image' failed
```

**Comment by anyasabo** [comment]
jenkins test this please

**Comment by charith-elastic** [comment]
The main branch has changed quite a bit so I'll close this and incorporate the changes in to a new PR.

**Pull request closed without merging**
