### PR TITLE
Test for up2date kubectl version

### PR DESCRIPTION
**Pull request by ThoTischner**
Signed-off-by: Thomas Tischner <tti@bitsbeats.com>

If kubectl is installed without kustomize support make integration will break.
This PR will extend the makefile to check for up2date kubectl version and fail with a good error message if requirements are not met.

### CODE REVIEW

**Comment by ThoTischner** [comment]
CLA signed and commit got signature.

**Comment by thbkrkr** [comment]
> I'm a bit on the fence regarding adding additional checks in a Makefile that is already fairly complicated. I think I'd rather not.

Yes, let's not make the `Makefile` more complicated.

However, [hack/check-requisites.sh](https://github.com/elastic/cloud-on-k8s/blob/master/hack/check-requisites.sh) seems a good place for this check.

**Comment by charith-elastic** [comment]
I am closing this PR for now because the preference seems to be having this check in `hack/check-requisites.sh` instead. Please feel free to re-open if you have an alternative suggestion or wish to make the change to `hack/check-requisites.sh` yourself.

**Comment by ThoTischner** [comment]
@thbkrkr So you will implement the check or should I open a new PR ?

**Comment by thbkrkr** [comment]
@ThoTischner I'll take care of it, thank you.

**Pull request closed without merging**
