### PR TITLE
Fix  eck-diagnostics download run for each e2e test failure

### LINKED ISSUE #6948: Fail to run eck-diagnostics
Since #6363, `eck-diagnostics` is run after each failure in the e2e tests job where `go test` is running.

I saw two errors when running eck-diagnostics:
- `exec: "initialising gs-util": executable file not found in $PATH`

that happens when we try to do `gcloud auth activate-service-account ...`:

https://github.com/elastic/cloud-on-k8s/blob/28081053429237cf97b93092122d927dc483e2cc/test/e2e/test/diagnostics.go#L60-L63

and a second which is most likely the consequence of the first:
- `Copying file:///tmp/eck-diagnostics-eck-e2e-stack-8-9-0-snap-gvvp-217-TestFilebeatDefaultConfig-ES_data_should_pass_validations.zip [Content-Type=application/zip]... AccessDeniedException: 403 Access denied.`

Log from [nightly/builds/217](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/217#0188dfec-e18a-4ab9-b938-04ce543b4953):
```
=== RUN   TestFilebeatDefaultConfig/ES_data_should_pass_validations
Retries (30m0s timeout): ...............................................
    step.go:51:
                Error Trace:    /go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/utils.go:94
                Error:          Received unexpected error:
                                hit count should be more than 0 for /*beat*/_search?q=agent.type:filebeat
                Test:           TestFilebeatDefaultConfig/ES_data_should_pass_validations
{
    "log.level": "error",
    "@timestamp": "2023-06-22T01:44:45.731Z",
    "message": "continuing with additional tests",
    "service.version": "0.0.0-SNAPSHOT+00000000",
    "service.type": "eck",
    "ecs.version": "1.4.0",
    "error": "test failure",
    "error.stack_trace": "github.com/elastic/cloud-on-k8s/v2/test/e2e/test.StepList.RunSequential\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/step.go:52\ngithub.com/elastic/cloud-on-k8s/v2/test/e2e/beat.TestFilebeatDefaultConfig\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/beat/config_test.go:50\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1576"
}
{
    "log.level": "info",
    "@timestamp": "2023-06-22T01:44:45.737Z",
    "log.logger": "e2e",
    "message": "running eck-diagnostics job",
    "service.version": "0.0.0-SNAPSHOT+00000000",
    "service.type": "eck",
    "ecs.version": "1.4.0"
}
{
    "log.level": "error",
    "@timestamp": "2023-06-22T01:44:45.737Z",
    "log.logger": "e2e",
    "message": "while running",
    "service.version": "0.0.0-SNAPSHOT+00000000",
    "service.type": "eck",
    "ecs.version": "1.4.0",
    "cmd": "initialising gs-util",
    "error": "exec: \"initialising gs-util\": executable file not found in $PATH, stderr: ",
    "error.stack_trace": "github.com/elastic/cloud-on-k8s/v2/test/e2e/test.run\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/diagnostics.go:51\ngithub.com/elastic/cloud-on-k8s/v2/test/e2e/test.maybeRunECKDiagnostics.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/diagnostics.go:62\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:74\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:65\ngithub.com/elastic/cloud-on-k8s/v2/test/e2e/test.maybeRunECKDiagnostics\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/diagnostics.go:61\ngithub.com/elastic/cloud-on-k8s/v2/test/e2e/test.StepList.RunSequential\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/step.go:59\ngithub.com /elastic/cloud-on-k8s/v2/test/e2e/beat.TestFilebeatDefaultConfig\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/beat/config_test.go:50\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1576"
}
{
    "log.level": "error",
    "@timestamp": "2023-06-22T01:45:29.824Z",
    "log.logger": "e2e",
    "message": "while running",
    "service.version": "0.0.0-SNAPSHOT+00000000",
    "service.type": "eck",
    "ecs.version": "1.4.0",
    "cmd": "gsutil",
    "error": "exit status 1, stderr: Copying file:///tmp/eck-diagnostics-eck-e2e-stack-8-9-0-snap-gvvp-217-TestFilebeatDefaultConfig-ES_data_should_pass_validations.zip [Content-Type=application/zip]...\n/ [0 files][    0.0 B/  3.0 MiB]                                                \r-\r- [0 files][  1.3 MiB/  3.0 MiB]                                                \r\\\rAccessDeniedException: 403 Access denied.\n",
    "error.stack_trace": "github.com/elastic/cloud-on-k8s/v2/test/e2e/test.run\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/diagnostics.go:51\ngithub.com/elastic/cloud-on-k8s/v2/test/e2e/test.maybeRunECKDiagnostics\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/diagnostics.go:74\ngithub.com/elastic/cloud-on-k8s/v2/test/e2e/test.StepList.RunSequential\n\t/go/src/github.com/elastic/c loud-on-k8s/test/e2e/test/step.go:59\ngithub.com/elastic/cloud-on-k8s/v2/test/e2e/beat.TestFilebeatDefaultConfig\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/beat/config_test.go:50\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1576"
}
    --- FAIL: TestFilebeatDefaultConfig/ES_data_should_pass_validations (1800.00s)
```

### PR DESCRIPTION
**Pull request by thbkrkr**
This makes the recent "test result file download" feature introduced in #6905 more generic with an "artefacts directory" where the job pod can write files which are then downloaded by the job manager when the pod is ready.

And uses it to collect the eck-diagnostics archives collected for each e2e test failure.

Resolves #6948.

### CODE REVIEW

**Comment by thbkrkr** [comment]
buildkite test this -f p=kind,s=8.9.0-SNAPSHOT,TEST_TIMEOUT=1m,s= TestFilebeatDefaultConfig

**Comment by thbkrkr** [comment]
buildkite test this -f p=kind,s=8.9.0-SNAPSHOT,TEST_TIMEOUT=2m,t=TestFilebeatDefaultConfig

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.9.0-SNAPSHOT,TEST_TIMEOUT=2m,t=TestFilebeatDefaultConfig

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.9.0-SNAPSHOT,TEST_TIMEOUT=2m,t=TestFilebeatDefaultConfig

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.9.0-SNAPSHOT,TEST_TIMEOUT=2m,t=TestFilebeatDefaultConfig

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.9.0-SNAPSHOT,TEST_TIMEOUT=2m,t=TestFilebeatDefaultConfig

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.9.0-SNAPSHOT,TEST_TIMEOUT=2m,t=TestFilebeatDefaultConfig

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.9.0-SNAPSHOT,TEST_TIMEOUT=2m,t=TestFilebeatDefaultConfig

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.9.0-SNAPSHOT,TEST_TIMEOUT=2m,t=TestFilebeatDefaultConfig

**Comment by thbkrkr** [comment]
buildkite test this

**Review by naemono — APPROVED** [review]
This looks good. 👍 Nice to see GCS buckets not being used now.

**Pull request merged**
