### PR TITLE
Remove duplicated info on supported versions

### PR DESCRIPTION
**Pull request by alaudazzi**
All in the title

### CODE REVIEW

**Comment by thbkrkr** [comment]
Given it's an important information, are we sure it's not worth to have the duplication?
I can imagine that someone will skip the quickstart.

**Comment by charith-elastic** [comment]
If we want to repeat this information in several places, maybe we should create a single document that can be brought in via an `include` statement.

**Comment by alaudazzi** [comment]
To overcome this, I propose to simply link the Quickstart to the Overview, with something like:

> Check out the Quickstart to know more about supported versions and get started with ECK.

**Comment by thbkrkr** [comment]
Superseeded by #1968.

**Pull request closed without merging**
