### PR TITLE
moves the annotation eck.k8s.elastic.co/license to values.yaml

### LINKED ISSUE #6261: Unable to deploy ECK stack due to license.
## Bug Report
**What did you do?**

Trying to deploy `eck-stack` based on [Elastic ECK Repo](https://github.com/elastic/cloud-on-k8s/tree/main/deploy)

**What did you expect to see?**

According to Elastic documentations, eck suppose to work with basic-tier and enterprise-tier customers.

So I expect to have Elastic stack resources running on my cluster w/ basic license (Free). Currently I'm able to deploy only `elastic-operator`.

Screen Shot 2022-12-28 at 23 12 32

Screen Shot 2022-12-28 at 23 13 08

Screen Shot 2022-12-28 at 23 15 37

**What did you see instead? Under which circumstances?**

I'm able to deploy elastic-operator but when I try to deploy eck-stack or any of eck chart got webhook denied due to license.

**Environment**

* ECK version:

	0.1.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* EKS 
	
```
$ kubectl version  v1.21.14
```

* Logs 1:
```
helm install es-kb-quickstart elastic/eck-stack -n elastic-stack 
Error: INSTALLATION FAILED: admission webhook "elastic-es-validation-v1.k8s.elastic.co" denied the request: Elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch" is invalid: metadata.annotations.eck.k8s.elastic.co/license: Invalid value: "enterprise": Enterprise license required but ECK operator is running on a Basic license
```

* Logs 2:
```
helm install elasticsearch elastic/eck-elasticsearch -n elastic-system
Error: INSTALLATION FAILED: admission webhook "elastic-es-validation-v1.k8s.elastic.co" denied the request: Elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch-eck-elasticsearch" is invalid: metadata.annotations.eck.k8s.elastic.co/license: Invalid value: "enterprise": Enterprise license required but ECK operator is running on a Basic license

### PR DESCRIPTION
**Pull request by michbeck100**
Moves the annotation eck.k8s.elastic.co/license to values.yaml to make it configurable. This fixes #6261.

### CODE REVIEW

**Comment by thbkrkr** [comment]
Hi, what value do you want to configure for this annotation and why?

**Comment by michbeck100** [comment]
I would like to override this annotation with
```yaml
eck.k8s.elastic.co/license: enterprise 
```

**Comment by thbkrkr** [comment]
Could you explain why do you need this? This annotation is to allow to request a certain level of license to be authorized to use certain ECK custom resources. It should no longer be necessary since ECK 2.12.0 because all of the ECK's custom resources, including when using Helm charts, are distributed under the basic license.

**Comment by michbeck100** [comment]
din't know that, sorry. Then this MR is no longer needed. Closing

**Pull request closed without merging**
