### PR TITLE
Add autoscaling usage reporting

### PR DESCRIPTION
**Pull request by barkbay**
This PR adds autoscaling usage reporting.

### CODE REVIEW

**Comment by idanmo** [comment]
@barkbay Perhaps we should add to telemetry what node roles the autoscaling policies are set for?

**Review by david-kow — APPROVED** [review]
LGTM

**Comment by barkbay** [comment]
> @barkbay Perhaps we should add to telemetry what node roles the autoscaling policies are set for?

Do you have any specific idea in mind about how the roles could be reported in the document ?
I'm not sure if something like that could do the job:

```yaml
   elasticsearches:
       autoscaling:
          resource_count: 2 # 2 clusters have autoscaling enabled
          roles:
            data_hot: 2 # Declared in 2 autoscaling policies
            ml: 1 # Declared in 1 autoscaling policy
            master: 1 # Even if there is no decider for master nodes the role could be included in autoscaling policies roles
      pod_count: 9
      resource_count: 2
```

**Comment by idanmo** [comment]
> Do you have any specific idea in mind about how the roles could be reported in the document ?
After discussing with @barkbay , we don't have a strong feeling about adding these metrics so I'm +1 with the current implementation.

**Pull request merged**
