### PR TITLE
Update eck-attributes.asciidoc

### PR DESCRIPTION
**Pull request by arslanbekov**
bump version in asciidoc
In doc: https://www.elastic.co/guide/en/cloud-on-k8s/1.0/k8s-quickstart.html#k8s-deploy-eck
```
error: unable to read URL "https://download.elastic.co/downloads/eck/1.0.0/all-in-one.yaml", server reported 404 Not Found, status code=404```

### CODE REVIEW

**Comment by arslanbekov** [comment]
Hi @sebgl, can you help me?

**Comment by barkbay** [comment]
Current version is [1.0-beta](https://www.elastic.co/guide/en/cloud-on-k8s/current/index.html)
1.0 will be released soon

**Comment by arslanbekov** [comment]
@barkbay Maybe need fix doc? Now instruction return 404.
`30 dec 2019` all works.

**Comment by anyasabo** [comment]
@arslanbekov as mentioned the docs linked are for an unreleased version, it will be fixed upon release

**Pull request closed without merging**
