### PR TITLE
[6716] Helm chart refactoring

### PR DESCRIPTION
**Pull request by Unknovvn**
Use `with` syntax in Helm Charts.

Resolves https://github.com/elastic/cloud-on-k8s/issues/6716 .

### CODE REVIEW

**Comment by thbkrkr** [comment]
Hi @Unknovvn, there is nothing special to do to trigger the review. All pull requests are usually reviewed within a week of being opened, but this depends on the priorities at the time. Thank you for the contribution and for your understanding.

**Comment by thbkrkr** [comment]
buildkite test this

**Review by thbkrkr — CHANGES_REQUESTED** [review]
Looks good!

There is just a small problem when the labels are included in a `{{ with }}` because the scope has changed.
```
> make helm-test
...
==> Linting .
[ERROR] templates/: template: eck-agent/templates/cluster-role.yaml:8:8: 
  executing "eck-agent/templates/cluster-role.yaml" at <include "elasticagent.labels" .>:
    error calling include: template: eck-agent/templates/_helpers.tpl:37:18: 
      executing "elasticagent.labels" at <include "elasticagent.chart" .>: 
        error calling include: template: eck-agent/templates/_helpers.tpl:30:25:
          executing "elasticagent.chart" at <.Chart.Name>: 
            nil pointer evaluating interface {}.Name

Ensuring dependencies are updated for eck-agent chart.
Running 'helm lint' on eck-agent chart.
engine.go:189: [INFO] Fail: At least one of daemonSet or deployment is required
==> Linting .
```

The global scope must be used now:

```diff
-    {{- include "elasticagent.labels" . | nindent 4 }}
+    {{- include "elasticagent.labels" $ | nindent 4 }}
```

In:
- deploy/eck-agent/templates/cluster-role-binding.yaml
- deploy/eck-agent/templates/cluster-role.yaml
- deploy/eck-agent/templates/elastic-agent.yaml
- deploy/eck-beats/templates/cluster-role-binding.yaml
- deploy/eck-beats/templates/cluster-role.yaml
- deploy/eck-fleet-server/templates/cluster-role-binding.yaml
- deploy/eck-fleet-server/templates/cluster-role.yaml
- deploy/eck-fleet-server/templates/service-account.yaml

**Comment by Unknovvn** [comment]
I actually missed `make helm-test` command. Will implement requested changes and test it accordingly today. Thanks for the review!

**Comment by thbkrkr** [comment]
buildkite test this

**Comment by thbkrkr** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by thbkrkr — APPROVED** [review]
LGTM, thanks for the contribution!

**Pull request merged**
