### PR TITLE
Upgrade go.uber.org/zap to 1.12.0

### PR DESCRIPTION
**Pull request by racevedoo**
Simple dependency upgrade. No breaking changes, check https://github.com/uber-go/zap/releases

### CODE REVIEW

**Comment by charith-elastic** [comment]
Jenkins test this please

**Comment by charith-elastic** [comment]
The notice file needs to be updated by running `make generate`.

**Comment by racevedoo** [comment]
@charith-elastic done!

**Comment by charith-elastic** [comment]
Jenkins test this please

**Pull request merged**
