### PR TITLE
Fix ubi8 suffix in operatorhub template

### PR DESCRIPTION
**Pull request by barkbay**
I think there is a discrepancy between the UBI image name in the [Makefile](https://github.com/elastic/cloud-on-k8s/blob/77c607ac4794f773e8a784f0bf40d78406f2b76f/Makefile#L50):

```Makefile
OPERATOR_IMAGE_UBI           ?= $(BASE_IMG)-ubi:$(IMG_VERSION)
```

And the one referenced in the operator hub template.

### CODE REVIEW

**Comment by barkbay** [comment]
> Hm I think the rationale behind ubi8 was to be aligned with what the stack images use as suffix.

Does it mean that the `Makefile` should be updated instead?

**Comment by thbkrkr** [comment]
Yes. https://github.com/elastic/cloud-on-k8s/blob/77c607ac4794f773e8a784f0bf40d78406f2b76f/Makefile#L50 is an oversight from #5580.

It works anyway because we are using the image published in the Docker Hub.

> grep "OPERATOR_DOCKERHUB.*elastic" Makefile              
OPERATOR_DOCKERHUB_IMAGE     ?= docker.io/elastic/$(IMG_NAME):$(IMG_VERSION)
OPERATOR_DOCKERHUB_IMAGE_UBI ?= docker.io/elastic/$(IMG_NAME)-ubi8:$(IMG_VERSION)
                                                                                                                                                                                  
> grep "operatorRepo.*elastic" hack/operatorhub/config.yaml
    operatorRepo: docker.elastic.co/eck/eck-operator
    operatorRepo: docker.elastic.co/eck/eck-operator
    operatorRepo: registry.connect.redhat.com/elastic/eck-operator
```

**Comment by barkbay** [comment]
> It works anyway because we are using the image published in the Docker Hub.

```
docker pull docker.elastic.co/eck/eck-operator-ubi8:2.3.0-bc1
Error response from daemon: manifest for docker.elastic.co/eck/eck-operator-ubi8:2.3.0-bc1 not found: manifest unknown: manifest unknown
```

while:

```
docker pull docker.elastic.co/eck/eck-operator-ubi:2.3.0-bc1                                                                           
2.3.0-bc1: Pulling from eck/eck-operator-ubi
Digest: sha256:cc9932a011b3a8cc7e09374334a3aca94eb1cc38950c48e73a5c4f09795d8712
Status: Image is up to date for docker.elastic.co/eck/eck-operator-ubi:2.3.0-bc1
docker.elastic.co/eck/eck-operator-ubi:2.3.0-bc1
```

Also I cannot find UBI images in [Docker Hub](https://registry.hub.docker.com/r/elastic/eck-operator/tags).

**Comment by thbkrkr** [comment]
My bad, yes, it's indeed broken! My eyes betrayed me: `docker.io/elastic` != `docker.elastic.co`

**Review by thbkrkr — APPROVED** [review]

**Comment by barkbay** [comment]
> Do we need to retroactively need to push a ubi8 image for the previous release?

I don't _think_ it is needed given that there was a single image (`docker.elastic.co/eck/eck-operator:2.2.0`) based on UBI 8.5

**Pull request merged**
