### PR TITLE
Use precondition when deleting secrets

### LINKED ISSUE #5249: [BUG] Elastic operator mistakenly deletes the secret objects when seeing a stale cluster state
## Bug Report
We find that when the elastic operator, when seeing stale cluster state, can mistakenly delete the "soft-owned" secret objects used for storing user passwords and TLS certificates.

**What did you do?**
We ran a simple workload with the elastic operator that:
1. create an elasticsearch cluster `elasticsearch`
2. delete the `elasticsearch` 
3. recreate the `elasticsearch`

**What did you expect to see?**
After recreation, the `elasticsearch` and its owned objects should become stable without unexpected object deletion.

**What did you see instead? Under which circumstances?**
We find that three secret objects `-es-elastic-user`, `-es-http-certs-public`, `-es-transport-certs-public` (used for storing user passwords and TLS certificates) are mistakenly deleted by the operator after recreating `elasticsearch`. The unexpected deletion is caused by the operator seeing a stale cluster state from an apiserver. After further inspection, we identified the concrete steps that trigger the bug:
1. When deleting the `elasticsearch`, the operator successfully deletes all the "soft-owned" secrets.
2. After recreating the `elasticsearch`, the operator creates the three secrets again.
3. The operator crashes and restarts (e.g., due to a machine reboot) and connects to a stale apiserver. The apiserver is not updated with the most updated cluster state, and has a stale view where the `elasticsearch` is deleted but the secrets exist (from step 1)
4. After restart, the operator finds that the `elasticsearch` is missing from the stale apiserver, and invokes `GarbageCollectSoftOwnedSecrets` to delete the three secrets that are currently in use.

**Environment**

* ECK version:

	660bc92fbfca469af552a833d8f6a4834c629649

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise: v1.18.9

* Logs:
After recreating the `elasticsearch` we see the following logs showing that the operator is garbage collecting the secrets, which is not expected:
```
{"log.level":"info","@timestamp":"2022-01-14T01:25:00.681Z","log.logger":"generic-reconciler","message":"Garbage collecting secret","service.version":"2.0.0-SNAPSHOT+3cba748e","service.type":"eck","ecs.version":"1.4.0","namespace":"default","secret_name":"elasticsearch-cluster-es-transport-certs-public","owner_name":"elasticsearch-cluster","owner_kind":"Elasticsearch"}
...
{"log.level":"info","@timestamp":"2022-01-14T01:25:00.686Z","log.logger":"generic-reconciler","message":"Garbage collecting secret","service.version":"2.0.0-SNAPSHOT+3cba748e","service.type":"eck","ecs.version":"1.4.0","namespace":"default","secret_name":"elasticsearch-cluster-es-http-certs-public","owner_name":"elasticsearch-cluster","owner_kind":"Elasticsearch"}
...
{"log.level":"info","@timestamp":"2022-01-14T01:25:00.690Z","log.logger":"generic-reconciler","message":"Garbage collecting secret","service.version":"2.0.0-SNAPSHOT+3cba748e","service.type":"eck","ecs.version":"1.4.0","namespace":"default","secret_name":"elasticsearch-cluster-es-elastic-user","owner_name":"elasticsearch-cluster","owner_kind":"Elasticsearch"}
```

* Additional information:
The staleness problem can be alleviated by setting the UID of the secret object in the `precondition` when deleting the objects in `GarbageCollectSoftOwnedSecrets`. So that k8s will find the precondition is not satisfied if the secret objects observed by the operator are also stale and refuses the deletion.
We are willing to send a PR to help fix this problem.

### PR DESCRIPTION
**Pull request by srteam2020**
Fix #5249 

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/cloud-on-k8s/tree/main/CONTRIBUTING.md)?
- If you submit code, is your pull request against main? We recommend pull requests against main. We will backport them as needed.

### CODE REVIEW

**Comment by pebrc** [comment]
Hey thanks for the PR ! You would have to sign the CLA linked above in the checks section in order for use to merge the PR. 

Also I think we would want to add the same predicate here: 
https://github.com/elastic/cloud-on-k8s/blob/9be005d2a4b6e26f98ff9c520ea53ae4d6cc9455/pkg/controller/common/reconciler/secret.go#L213

And should maybe add a unit test to the existing test cases testing the new behaviour.

**Comment by pebrc** [comment]
Jenkins test this please

**Comment by srteam2020** [comment]
Hello @pebrc we have updated the PR but we didn't find a good way to write unit test to test the new behavior. Do you have any suggestion on that? What should we do to help merge this PR?

**Comment by pebrc** [comment]
Hey @srteam2020 if you could add the precondition also to the line I linked above https://github.com/elastic/cloud-on-k8s/pull/5273#issuecomment-1019961582 

Once that's done I think I would be OK to merge this as is.

**Comment by srteam2020** [comment]
Sorry I missed that. Just updated the PR again.

**Review by pebrc — APPROVED** [review]
LGTM!

**Comment by pebrc** [comment]
Jenkins test this please

**Pull request merged**
