### PR TITLE
[DOCS] Switched hardcoded 7.16 links to current

### PR DESCRIPTION
**Pull request by debadair**
Updated the hardcoded 7.16 links to use current.

DO NOT MERGE UNTIL 7.16 is released.

### CODE REVIEW

**Review by nrichers — COMMENTED** [review]
@alaudazzi I noticed that we hardcode links to `current` which can be problematic. Ideally, we'd use a shared version file for this stuff. It's not a perfect solution, but one step up from hardcoding links directly. I wonder if this might not be something to raise with the ECK team at some point?

**Review by nrichers — APPROVED** [review]
LGTM. 🐢

**Comment by debadair** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by nrichers** [comment]
@elasticcloudmachine update branch

**Comment by debadair** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
