### PR TITLE
Add password hash (cached) generator

### PR DESCRIPTION
**Pull request by barkbay**
Attempt to mitigate and close https://github.com/elastic/cloud-on-k8s/issues/6076

The cache size is arbitrarily set to 5 `x` the number of workers. It can be changed (and disabled) via a configuration flag. We could dynamically resize the cache according to the number of managed resources, but I thought it was a bit involved for a first implementation.

From a security point of view:
* It means that passwords and hashes are stored in memory for a longer time, I don't think it is a concern as they are already both in memory, and reading the process memory would require the server to be compromised.
* Password comparison is no longer "time consistent", but I can't a see how an attacker could take advantage of this behaviour in the context of a reconciliation loop.

### CODE REVIEW

**Comment by barkbay** [comment]
Jenkins test this please

**Review by pebrc — APPROVED** [review]
LGTM I was conflicted whether such a low-level implementation detail should be exposed through a dedicated flag it feels like something that should go into some form of internal performance tuning settings.  But I guess we don't have such a concept so I am good with the choice made here.

**Comment by pebrc** [comment]
I just realised an entry for the new flag in the documentation page for the operator flags is missing.

**Comment by barkbay** [comment]
> I just realised an entry for the new flag in the documentation page for the operator flags is missing.

It makes me realise that I forgot to add the parameter in the Helm chart generated configmap: https://github.com/elastic/cloud-on-k8s/pull/6080/commits/6673a77ed7ff31bc5aaaf39bd4cb0faef30db517 😄

**Review by pebrc — APPROVED** [review]

**Pull request merged**
