### PR TITLE
Avoid lossy type conversion when parsing number of available replicas

### PR DESCRIPTION
**Pull request by racevedoo**
There was a TODO on a lossy type conversion when reading the number of available replicas from k8s. This aims to fix it by using int64 instead of int on `ReconcilerStatus.AvailableNodes`

### CODE REVIEW

**Comment by thbkrkr** [comment]
jenkins test this please

**Comment by thbkrkr** [comment]
The [CI build](https://devops-ci.elastic.co/job/cloud-on-k8s-pr/1962/consoleText) failed:
```go
09:50:06  Error: dirty local changes
09:50:06   M config/crds/apm.k8s.elastic.co_apmservers.yaml
09:50:06   M config/crds/elasticsearch.k8s.elastic.co_elasticsearches.yaml
09:50:06   M config/crds/kibana.k8s.elastic.co_kibanas.yaml
```
Please `make generate` to update the CRDs according to this change.

**Comment by racevedoo** [comment]
oops, sorry! should be fixed now, can anyone trigger a build?

**Comment by thbkrkr** [comment]
jenkins test this please

**Comment by charith-elastic** [comment]
Since `availableNodes` is basically a synonym for [`DeploymentStatus.AvailableReplicas`](https://godoc.org/k8s.io/api/apps/v1#DeploymentStatus), shouldn't the type be `int32`? That should get rid of some of the upcasts in the code.

**Comment by racevedoo** [comment]
@charith-elastic maybe. I thought of using `int64` so we don't have to do any "lossy" casts. The only ones that could be lossy are the `len` ones, which probably won't be an issue to convert to int32. If the `len` is larger than an `int32`, we have bigger issues hehehe. WDYT?

**Comment by charith-elastic** [comment]
If the underlying Kubernetes primitive uses int32, then I don't see how we would lose any information from the return value of the `len` function. Besides, I don't think Kubernetes would be able to handle over 2 billion pods without something else breaking in the control plane first -- so this is probably not an issue we need to be worried about any time soon. :)

Unless we ran on some strange architecture, I think even `int` is guaranteed to be at least 32 bits wide. However, for completeness sake, it would be good to use the correct data type -- which is `int32` in this particular case.

**Comment by thbkrkr** [comment]
jenkins test this please

**Comment by thbkrkr** [comment]
jenkins test this please

**Pull request merged**
