### PR TITLE
[DOC] Add 2.6 and 2.7 to the triggered restart list

### PR DESCRIPTION
**Pull request by barkbay**
Fixes https://github.com/elastic/cloud-on-k8s/issues/6765

### CODE REVIEW

**Review by pebrc — APPROVED** [review]
Surprised that we missed this.

**Comment by thbkrkr** [comment]
Same, I swear I checked that there was no restart when updating from `2.6` to `2.7` with a very simple stack (quickstart). Maybe it happens with a more complex stack.

**Comment by BenB196** [comment]
> Same, I swear I checked that there was no restart when updating from `2.6` to `2.7` with a very simple stack (quickstart). Maybe it happens with a more complex stack.

FYI, my issue might've been confusing, I've upgraded a few ~10 ECK operators, and didn't see an restart from 2.6 -> 2.7, but did see a restart for 2.5 -> 2.6 and 2.5 -> 2.7, so might only be 2.6 that causes a restart.

(Weird side note, 2.7 does cause some beats/agents to be restarted, but I don't think that is a documented thing anywhere)

**Comment by barkbay** [comment]
> didn't see a restart from 2.6 -> 2.7,

I did a quick test before opening the PR. While Elasticsearch Pods were not restarted in that context, it was not the case for the Kibana ones which were actually restarted.

> Weird side note, 2.7 does cause some beats/agents to be restarted, but I don't think that is a documented thing anywhere

Same for Kibana, that's why I included 2.7 in that list, which I did not consider as restricted to Elasticsearch.

**Pull request merged**
