### PR TITLE
Fix yaml kibana example in saml authentication doc

### PR DESCRIPTION
**Pull request by JohannesMahne**
Fixing hierarchy of Kibana yaml example in SAML authentication doc.

### CODE REVIEW

**Review by pebrc — APPROVED** [review]

**Comment by pebrc** [comment]
@JohannesMahne thanks for your PR can you please re-target it to the `main` branch thanks! We can then later back port it to all affected versions.

**Comment by JohannesMahne** [comment]
@pebrc - can you please assist? It seems I am not authorised to merge this PR to main.

**Comment by pebrc** [comment]
Can you rebase your change on `main`? Or open a new PR if that's easier.

**Comment by thbkrkr** [comment]
I'll take care of the rebase.

**Review by thbkrkr — APPROVED** [review]

**Pull request merged**
