### PR TITLE
Run E2E tests using regexp and tags extracted from PR comment

### PR DESCRIPTION
**Pull request by thbkrkr**
This commit allows to trigger the full pr job (which uses the `e2e-tests-main-gke` pipeline) with parameters extracted from the PR comment.

2 parameters are added to the pipeline with default values so that the `cloud-on-k8s-e2e-tests-main` [job](https://github.com/elastic/cloud-on-k8s/blob/41440481689cc5071ca9d5b1f949aa7c943f5686/.ci/jobs/e2e-tests-main-gke.yml#L21) which also uses the `e2e-tests-main-gke` pipeline is not impacted: `TESTS_MATCH` (default: `^Test`) and `E2E_TAGS` (default: `e2e`).

Parameters are extracted from the PR comment following the format: `foo bar key1=value1 key2=value2 key3=value3...`

I kept the variable names as defined in the Makefile for the job parameters but I chose to use shortnames for the PR comment:
- `match=<..>` for `TESTS_MATCH`
- `tags=<..>` for `E2E_TAGS`

Tell me if you prefer to keep the names aligned?

I also kept the `run full pr build` phrase to trigger the job and added `run/e2e-tests` which seems to me a little more appropriate. also because I often make the mistake of writing `job` instead of `build`.

Example:
- `run/e2e-tests match=TestESStackMonitoring`
- `run/e2e-tests tags=beat`

### CODE REVIEW

**Comment by thbkrkr** [comment]
run full pr job match=TestESStackMonitoring

**Comment by thbkrkr** [comment]
run full pr build match=TestESStackMonitoring

**Comment by thbkrkr** [comment]
run full pr build match=TestESStackMonitoring

**Comment by thbkrkr** [comment]
run full pr build match=TestESStackMonitoring

**Comment by thbkrkr** [comment]
run full pr build match=TestESStackMonitoring

**Comment by thbkrkr** [comment]
run full pr build match=TestESStackMonitoring tags=es

**Comment by thbkrkr** [comment]
run full pr build match=TestESStackMonitoring

**Comment by thbkrkr** [comment]
run full pr build tags=kb

**Review by naemono — APPROVED** [review]
This sounds/looks great to me.  Only comment I would have is to update the documentation for using this feature.  I think it currently lives in `CONTRIBUTING.md`.  May be in others as well.

**Pull request merged**
