### PR TITLE
#2815 refactor deployer initialisms to Full Caps

### PR DESCRIPTION
**Pull request by townsymush**
**Issue:**#2815 

**Changes:**

- Ocp initialism to OCP

- Gke initialism to GKE

- Acr initialism to ACR

- Ssd initialism to SSD

- Aks initialism to AKS

**Notes**

- Ran unit and integration tests on Ubuntu 18.04 (No access to Mac, if possible could someone please test?)

- Lint fails in pkg/controller/enterprisesearch/config_test.go (Also fails in Master. I can look into resolving this in this PR if not already fixed?)

* First issue #BeKind

### CODE REVIEW

**Comment by anyasabo** [comment]
jenkins test this please

**Comment by anyasabo** [comment]
jenkins test this please

**Comment by townsymush** [comment]
Is there something I need to do with this? If so could someone explain please?

**Comment by anyasabo** [comment]
jenkins test this please

**Comment by thbkrkr** [comment]
@townsymush Sorry for the delay, the change breaks something that was not easy to see. To avoid leaking secrets, very few errors are outputed by the deployer.

The change in this PR breaks the mechanism for overriding the default plans.

I don't know what's going on but my gut feeling would be that `imdario/mergo` behaves strangely. 
It seems to no longer take into account the lowercase tag field when the field is in uppercase (`ABC string `yaml:"abc"`). With the field in uppercase, the override works only with `ABC: override` or `aBC: override`.

```go
package main

import (
	"fmt"
	"os"

	"github.com/imdario/mergo"
)

type Lowercase struct {
	Abc string `yaml:"abc"`
}

type Uppercase struct {
	ABC string `yaml:"abc"`
}

type Uppercase2 struct {
	ABC string `yaml:"ABC"`
}

func main() {
	lowercaseOverride := map[string]interface{}{
		"abc": "x",
	}

	l := Lowercase{}
	err := mergo.Map(&l, lowercaseOverride, mergo.WithOverride)
	if err != nil {
		os.Exit(1)
	}
	fmt.Println("lowercaseOverride> Lowercase:", l)

	u := Uppercase{}
	err = mergo.Map(&u, lowercaseOverride, mergo.WithOverride)
	if err != nil {
		os.Exit(1)
	}
	fmt.Println("lowercaseOverride> Uppercase:", u)

	uppercaseOverride := map[string]interface{}{
		"ABC": "x",
	}

	l = Lowercase{}
	err = mergo.Map(&l, uppercaseOverride, mergo.WithOverride)
	if err != nil {
		os.Exit(1)
	}
	fmt.Println("uppercaseOverride> Lowercase:", l)

	u = Uppercase{}
	err = mergo.Map(&u, uppercaseOverride, mergo.WithOverride)
	if err != nil {
		os.Exit(1)
	}
	fmt.Println("uppercaseOverride> Uppercase:", u)

	u2 := Uppercase2{}
	err = mergo.Map(&u2, uppercaseOverride, mergo.WithOverride)
	if err != nil {
		os.Exit(1)
	}
	fmt.Println("uppercaseOverride> Uppercase2:", u2)
}
```

```sh
lowercaseOverride> Lowercase: {x}
lowercaseOverride> Uppercase: {}

uppercaseOverride> Lowercase: {}
uppercaseOverride> Uppercase: {x}
uppercaseOverride> Uppercase2: {x}
```

**Comment by townsymush** [comment]
Thanks for the info.

I think I need to spend some more time getting through the codebase. If someone else wanted to pick it up in the mean time then all good.

**Pull request closed without merging**
