### PR TITLE
update ocp networktype from OpenShiftSDN to OVNKubernetes

### PR DESCRIPTION
**Pull request by kvalliyurnatt**
update ocp networkType since we saw the nightly fail with 
```
level=error msg=failed to fetch Metadata: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: networking.networkType: Invalid value: "OpenShiftSDN": networkType OpenShiftSDN is not supported, please use OVNKubernetes

```

### CODE REVIEW

**Comment by kvalliyurnatt** [comment]
buildkite test this -f p=ocp,TESTS_MATCH=TestSmoke -m s=8.14.0-SNAPSHOT

**Comment by kvalliyurnatt** [comment]
buildkite test this -f p=ocp,TESTS_MATCH=TestSmoke -m s=8.14.0-SNAPSHOT

**Comment by kvalliyurnatt** [comment]
buildkite test this -f p=ocp,TESTS_MATCH=TestSmoke -m s=8.14.0-SNAPSHOT

**Comment by naemono** [comment]
buildkite test this -f p=ocp,TESTS_MATCH=TestSmoke -m s=8.14.0-SNAPSHOT

**Review by naemono — APPROVED** [review]
If ocp tests pass, then lgtm.

**Comment by kvalliyurnatt** [comment]
moved version back to 4.14.12, since 4.15.* seems to suffer from a bug that is preventing clusters from coming up. Tested this locally on my dev env
The issue we are hitting is exactly the same as this
https://github.com/openshift/installer/issues/7146#issuecomment-1912136826
and the workaround mentioned here does work, but this not doable as part of our automated tests.

Still switching over the network_type since the current one we are using is deprecated and removed in 4.15

**Comment by kvalliyurnatt** [comment]
buildkite test this -f p=ocp,TESTS_MATCH=TestSmoke -m s=8.14.0-SNAPSHOT

**Review by pebrc — APPROVED** [review]

**Comment by kvalliyurnatt** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|2.13|[](https://github.com/elastic/cloud-on-k8s/pull/7767)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
