### PR TITLE
Update elasticsearch-spec.asciidoc

### PR DESCRIPTION
**Pull request by SeanPlacchetti**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/cloud-on-k8s/tree/master/CONTRIBUTING.md)?
- If you submit code, is your pull request against master? We recommend pull requests against master. We will backport them as needed.

### CODE REVIEW

**Comment by artemnikitin** [comment]
jenkins test this please

**Comment by sebgl** [comment]
Hi @SeanPlacchetti,
While this change makes sense, I think it would break our current documentation website. See https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-es-secure-settings.html: clicking on `How to create automated snapshots` does redirect to the correct documentation page.

I think there is a mismatch between our doc website, for which webpages and redirection is based on doc section IDs: `[id="{p}-how-to-snapshot"]`, and what you may expect from looking at the file tree (`snapshots.asciidoc`).

**Comment by sebgl** [comment]
I think it would make sense to rename the `k8s-how-to-snapshot` section to a simpler `snapshots`.
@alaudazzi any thoughts?

**Comment by alaudazzi** [comment]
Close in favour of #1509.

**Pull request closed without merging**
