### PR TITLE
Delete old shutdowns before creating new ones

### LINKED ISSUE #5628: Shutdown records left standing after node has been restarted reduce number of replicas for `auto_expand_replicas`
Nodes with node shutdown records reduce the number of available nodes that the `auto_expand_replicas` mechanism in Elasticsearch takes into account when adjusting the replicas which happens on each re-route task e.g. after a node has left the cluster. 

If we have a three node cluster with two shutdown records then the number of replicas calculated for `auto_expand_replicas` is `0` if the remaining replica comes to lie on a node scheduled for shutdown then the cluster goes `RED`


Console grab from a manual reproduction:
```sh
~/s/e/shutdown (master)> k8surl PUT _ _nodes/aCDmIS53SV6kIW4kLUdkrA/shutdown request.json
{"acknowledged":true}⏎                                                                                                                                                                                              ~/s/e/shutdown (master)> k8surl PUT _ _nodes/Kt6rd7L4Qpe7s8Z8n-VT2A/shutdown request.json
{"acknowledged":true}⏎                                                                                                                                                                                              ~/s/e/shutdown (master)> k8surl GET _ _nodes/shutdown | jq
{
  "nodes": [
    {
      "node_id": "aCDmIS53SV6kIW4kLUdkrA",
      "type": "RESTART",
      "reason": "manual test",
      "allocation_delay": "5m",
      "shutdown_startedmillis": 1651149105690,
      "status": "COMPLETE",
      "shard_migration": {
        "status": "COMPLETE",
        "shard_migrations_remaining": 0,
        "explanation": "no shard relocation is necessary for a node restart"
      },
      "persistent_tasks": {
        "status": "COMPLETE"
      },
      "plugins": {
        "status": "COMPLETE"
      }
    },
    {
      "node_id": "Kt6rd7L4Qpe7s8Z8n-VT2A",
      "type": "RESTART",
      "reason": "manual test",
      "allocation_delay": "5m",
      "shutdown_startedmillis": 1651149113387,
      "status": "COMPLETE",
      "shard_migration": {
        "status": "COMPLETE",
        "shard_migrations_remaining": 0,
        "explanation": "no shard relocation is necessary for a node restart"
      },
      "persistent_tasks": {
        "status": "COMPLETE"
      },
      "plugins": {
        "status": "COMPLETE"
      }
    }
  ]
}
~/s/e/shutdown (master)> k8surl GET _ _cat/shards
data-integrity-check 2 p STARTED 1 3.9kb 10.73.50.59 test-mutation-http-to-https-64nh-es-masterdata-2
data-integrity-check 2 r STARTED 1 3.9kb 10.73.49.45 test-mutation-http-to-https-64nh-es-masterdata-1
data-integrity-check 1 p STARTED 4 3.9kb 10.73.50.59 test-mutation-http-to-https-64nh-es-masterdata-2
data-integrity-check 1 r STARTED 4 3.9kb 10.73.48.36 test-mutation-http-to-https-64nh-es-masterdata-0
data-integrity-check 0 r STARTED 0  225b 10.73.48.36 test-mutation-http-to-https-64nh-es-masterdata-0
data-integrity-check 0 p STARTED 0  225b 10.73.49.45 test-mutation-http-to-https-64nh-es-masterdata-1
.geoip_databases     0 r STARTED         10.73.48.36 test-mutation-http-to-https-64nh-es-masterdata-0
.geoip_databases     0 p STARTED         10.73.49.45 test-mutation-http-to-https-64nh-es-masterdata-1
~/s/e/shutdown (master)> k get pods
NAME                                               READY   STATUS    RESTARTS   AGE
test-mutation-http-to-https-64nh-es-masterdata-0   1/1     Running   0          65s
test-mutation-http-to-https-64nh-es-masterdata-1   1/1     Running   0          22m
test-mutation-http-to-https-64nh-es-masterdata-2   1/1     Running   0          24m
~/s/e/shutdown (master)> k delete pod test-mutation-http-to-https-64nh-es-masterdata-0
pod "test-mutation-http-to-https-64nh-es-masterdata-0" deleted
^[[A^[[B⏎                                                                                                                                                                                                           ~/s/e/shutdown (master)> k8surl GET _ _cat/shards
data-integrity-check 2 p STARTED 1 3.9kb 10.73.50.59 test-mutation-http-to-https-64nh-es-masterdata-2
data-integrity-check 2 r STARTED 1 3.9kb 10.73.49.45 test-mutation-http-to-https-64nh-es-masterdata-1
data-integrity-check 1 p STARTED 4 3.9kb 10.73.50.59 test-mutation-http-to-https-64nh-es-masterdata-2
data-integrity-check 1 r STARTED 4 3.9kb 10.73.48.37 test-mutation-http-to-https-64nh-es-masterdata-0
data-integrity-check 0 r STARTED 0  225b 10.73.48.37 test-mutation-http-to-https-64nh-es-masterdata-0
data-integrity-check 0 p STARTED 0  225b 10.73.49.45 test-mutation-http-to-https-64nh-es-masterdata-1
.geoip_databases     0 p STARTED         10.73.49.45 test-mutation-http-to-https-64nh-es-masterdata-1

```

Our current implementation unfortunately sometimes have transient states where two records exist because we clean up old records after creating new ones and even sometimes short circuit the reconciliation which prolongs the transient state even more.

### PR DESCRIPTION
**Pull request by pebrc**
Fixes #5628

Moves the cleanup at the beginning of the upgrade function to make sure we don't end up with left over shutdowns and then don't get to clean them up in time because we exit early after node deletions.

### CODE REVIEW

**Comment by pebrc** [comment]
run/e2e-tests tags=es

**Comment by pebrc** [comment]
I need to clean up the tests but I think the principle works. Just wanted to raise this already to run the e2e tests.

**Comment by pebrc** [comment]
Test failed due to an issue with the new pipeline. Will try to run manual tests for the time being.

**Comment by thbkrkr** [comment]
run/e2e-tests tags=es

**Comment by pebrc** [comment]
Screenshot 2022-04-28 at 21 35 49

Test run of all es e2e test was successful. There is a more ambitious version of this PR that simply moves the `maybeCompleteNodeUpgrades` function to the same position as the call to `nodeShutdown.Clear`. It has the advantage of keeping the clean up code together. I am still testing this locally but the current change set would be a minimal fix IMO.

**Review by naemono — APPROVED** [review]
Running test locally, but can't see a scenario where clearing old shutdowns where the node is back in the cluster at the start of any upgrade loop would cause future problems.

**Review by barkbay — APPROVED** [review]
LGTM 👍 
I did some manual testing while keeping an eye on `/_nodes/shutdown` to ensure that there was at most one shutdown record. Maybe this is something we could include in a test, ideally in a unit test or/and maybe along the [continuous health check](https://github.com/elastic/cloud-on-k8s/blob/99618dd12e61765f249e7fa666351cfeb3a8d791/test/e2e/test/elasticsearch/steps_mutation.go#L105-L118). (in another PR ofc)

**Comment by pebrc** [comment]
Thanks @barkbay  and @naemono for the quick reviews!

> Maybe this is something we could include in a test, ideally in a unit test or/and maybe along the [continuous health check](https://github.com/elastic/cloud-on-k8s/blob/99618dd12e61765f249e7fa666351cfeb3a8d791/test/e2e/test/elasticsearch/steps_mutation.go#L105-L118). (in another PR ofc)

Yes I think I am going to follow up on this PR with something a bit more comprehensive targeting the main branch/next release and will include improved e2e testing as well. I think your idea of an additional continuous health check is really good.

**Comment by pebrc** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|2.2|[](https://github.com/elastic/cloud-on-k8s/pull/5633)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
