### PR TITLE
[DOCS] Add workaround for Enterprise Search security context

### PR DESCRIPTION
**Pull request by leemthompo**
On ECK, Enterprise Search does not work with `readOnlyRootFilesystem: true`

This PR tries to document @TattdCodeMonkey's workaround.

### CODE REVIEW

**Review by ioanatia — APPROVED** [review]

**Comment by leemthompo** [comment]
@barkbay @thbkrkr @pebrc would y'all be able to give authorized approval for this docs PR? 🙏

**Review by barkbay — APPROVED** [review]
LGTM

**Comment by barkbay** [comment]
Thanks @leemthompo!

**Comment by leemthompo** [comment]
Thanks @barkbay! Forgot to ask about backporting this PR if you have any preferences?

**Comment by barkbay** [comment]
@leemthompo  I created a backport for 2.13 which is our current ECK version: https://github.com/elastic/cloud-on-k8s/pull/7911 Do you think we need to backport this to older versions?

**Comment by leemthompo** [comment]
Thanks @barkbay! I'm not sure if we should backport farther — @ppf2 do you have a preference here?

**Comment by pebrc** [comment]
I was wondering the same thing. But I wanted to check how big the war files are that are moved to an `emptyDir` if that is in GBs it is maybe not something we want to do by default?

**Pull request merged**
