### PR TITLE
handle io copy error

### PR DESCRIPTION
**Pull request by panguicai008**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/cloud-on-k8s/tree/main/CONTRIBUTING.md)?
- If you submit code, is your pull request against main? We recommend pull requests against main. We will backport them as needed.

### CODE REVIEW

**Review by barkbay — COMMENTED** [review]
Thanks for the PR.

IMHO error wrapping should be used to add some context to an error. I'm not sure that it is the case in your proposal, `failed to copy response body to buffer` feels a bit generic and I don't think it would help to understand the root cause of the error.

I think I would stick with the current implementation.

**Comment by panguicai008** [comment]
> Thanks for the PR.
> 
> IMHO error wrapping should be used to add some context to an error. I'm not sure that it is the case in your proposal, `failed to copy response body to buffer` feels a bit generic and I don't think it would help to understand the root cause of the error.
> 
> I think I would stick with the current implementation.

I want to deal with this error. The `makeRequest` function caller uses error wrapping, so I should output error directly? I can replace `%w` with`%v`, do you think so?

**Comment by panguicai008** [comment]
I just think that when an error may appear in a function, it should be handled. Like in other open source projects, this `io.Copy` error will also be polished. I don't pay much attention to what happens when error occurs. In addition, the purpose of reading this code is to generate bundle image from various versions of CSV, build catalog image, and prepare for privatization deployment without using the official operator hub

**Comment by thbkrkr** [comment]
Closing because the proposed change to wrap the error does not provide any real improvement over the current implementation.

**Pull request closed without merging**
