### PR TITLE
Remove stack image defintion feature and fix image overrides

### PR DESCRIPTION
**Pull request by pebrc**
Remove the unused stack versions feature from the e2e code. 
Reset the image when setting the version so that stateful builder code won't keep an image digest for a version previously set (see current test failures) 

```
// pseudo code
newBuilder {
.setVersion("8.9.0-SNPSHOT")
}
// version: "8.9.0-SNAPSHOT"
// image: docker.elastic.co/elasticsearch/elasticsearch@sha256:39599c71bd7446fc3c38f22462ba5c86ce65813c4ec38eb3b71bb876061351d4

b.setVersion("8.8.0")
// version: "8.8.0"
// image: docker.elastic.co/elasticsearch/elasticsearch@sha256:39599c71bd7446fc3c38f22462ba5c86ce65813c4ec38eb3b71bb876061351d4


// test is not actually running 8.8.0 at this point but still 8.9.0-SNAPSHOT
```

### CODE REVIEW

**Comment by pebrc** [comment]
buildkite test this -f p=gke,E2E_STACK_VERSION=8.9.0-SNAPSHOT,t=TestVersionUpgradeTwoNodesToLatest8x

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.9.0-SNAPSHOT,t=TestVersionUpgradeTwoNodesToLatest8x

**Comment by thbkrkr** [comment]
I spotted a small bug in the way we detect if we build `eck-dev` to perform e2e tests against SNAPSHOT stack versions. I did the bad assumption that we would write in the comment "s=8.9.0-SNAPSHOT" (the version with the shortcut) while we must also support "E2E_STACK_VERSION =8.9.0-SNAPSHOT".

https://github.com/elastic/cloud-on-k8s/blob/e3fa2fad671ed9105164df0966ce1dfae286ead0/.buildkite/scripts/common/trigger.sh#L60-L62

https://github.com/elastic/cloud-on-k8s/blob/e3fa2fad671ed9105164df0966ce1dfae286ead0/.buildkite/scripts/common/operator-image.sh#L54-L55

**Review by thbkrkr — APPROVED** [review]
LGTM

**Comment by pebrc** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|2.9|[](https://github.com/elastic/cloud-on-k8s/pull/6999)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
