### PR TITLE
Doc: Autoscalers are not yet supported by Logstash on ECK

### LINKED ISSUE #7820: Doc: Add messaging about autoscaling for Logstash on ECK
We've determined the need to include some information about autoscaling Logstash on ECK in order to: 
- let users know that we don't have a complete autoscaling answer _yet_, but it's coming
- provide some scaling guidance now so that users won't configure their instances in ways that are not ideal for adopting autoscaling when it is available

Possible placement: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-logstash-plugins.html#k8s-logstash-working-with-plugins-scaling

### PR DESCRIPTION
**Pull request by karenzone**
Fixes #7820

**PREVIEW:**  http://localhost:8000/guide/k8s-logstash-plugins.html#k8s-logstash-working-with-plugins-scaling

Screen Shot 2024-05-16 at 4 19 03 PM

### CODE REVIEW

**Comment by kvalliyurnatt** [comment]
@karenzone is this needed for the upcoming release ?

**Comment by karenzone** [comment]
> @karenzone is this needed for the upcoming release ? (2.13.0 that is scheduled for May21)

As this is just a note, I would think maybe not.  But I'll defer to @robbavey.  Rob, what do you think?

**Comment by robbavey** [comment]
@kvesthy We would prefer this to be in there, but if there are higher priority items that would prevent that, it could be added later

**Review by robbavey — APPROVED** [review]
LGTM

**Comment by karenzone** [comment]
@kvesthy, Rob has approved it, and I just merged `main` back into my branch.  We'll need an approval and merge by an ECK codeowner, and we'll be ready to go!

**Review by barkbay — APPROVED** [review]
> @karenzone is this needed for the upcoming release ? (2.13.0 that is scheduled for May21)

I think we can backport doc changes as soon as we think it is necessary. We could include this change in `2.13`, and also do a backport into `2.12` immediately.

**Comment by barkbay** [comment]
s / @kvesthy / @kvalliyurnatt , so many Karthik at Elastic 😄

**Comment by kvalliyurnatt** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|2.13|[](https://github.com/elastic/cloud-on-k8s/pull/7826)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
