### PR TITLE
Support RevisionHistoryLimit in Deployment and Daemonset for Elastic Agent

### LINKED ISSUE #5789: Support RevisionHistoryLimit in Deployment and Daemonset for Elastic Agents
## Proposal

As part of the `agents.agent.k8s.elastic.co` CRD under both deployment and daemonset RevisionHistoryLimit should be supported.

Deployment already supports `replicas`, `podTemplate` so adding a revisionHistoryLimit seems like a small lift.

**Use case. Why is this important?**

Being able to limit the number of `revisionHistoryLimit` matters for performance purposes, and cleaning up old replicasets, etc.

### PR DESCRIPTION
**Pull request by KnechtionsCoding**
Closes #5789 

I'm not sure why the tests are failing. But this is a start of a PR at least. I think I tracked down all the places this field was set for the agent.

### CODE REVIEW

**Comment by thbkrkr** [comment]
> the tests are failing
No, they haven't been executed yet,

Jenkins test this please

**Comment by KnechtionsCoding** [comment]
> > the tests are failing
> 
> No, they haven't been executed yet,
> 
> Jenkins test this please (which can only be invoked by Elastic folks).

No, they are failing locally. I just am not sure why. I didn't think I changed anything related to the one test failing. Sorry, I should have been more clear.

**Comment by thbkrkr** [comment]
> I just am not sure why. I didn't think I changed anything related to the one test failing. Sorry, I should have been more clear.

This is a difficult error to debug when you don't know. `TestReconcileAgent_Reconcile` failed because the Agent resource was not considered reconciled because with the new field the template hash we put in a label changed.

**Comment by thbkrkr** [comment]
Jenkins test this please

**Comment by thbkrkr** [comment]
Jenkins test this please

**Review by thbkrkr — APPROVED** [review]

**Comment by david-kow** [comment]
Excluding from release notes as title of https://github.com/elastic/cloud-on-k8s/pull/5818 covers this.

**Pull request merged**
