### PR TITLE
Rename resourceStatuses to details in StackConfigurationPolicy

### PR DESCRIPTION
**Pull request by kvalliyurnatt**
Renaming `resourcesStatuses` to `details` in the Stack config policy status to avoid conflicts during version upgrade from `2.10` to `2.11`.

Tested this with upgrade and this resolves the issue that was observed earlier. Also ran the e2e tests and unit tests locally. Everything seems to work as expected.

### CODE REVIEW

**Review by naemono — COMMENTED** [review]
I think you also need to update `docs/orchestrating-elastic-stack-applications/stack-config-policy.asciidoc`.

**Comment by naemono** [comment]
> I think you also need to update `docs/orchestrating-elastic-stack-applications/stack-config-policy.asciidoc`.

Oh, and some things under `hack/upgrade-test-harness`.

**Comment by naemono** [comment]
> Oh, and some things under `hack/upgrade-test-harness`.

Nevermind on this one, I'm wrong.

**Review by thbkrkr — APPROVED** [review]

**Review by pebrc — APPROVED** [review]
LGTM and fixed the issue in my test.

**Review by barkbay — APPROVED** [review]
LGTM

**Review by naemono — APPROVED** [review]
All good here as well.

**Comment by kvalliyurnatt** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|2.11|[](https://github.com/elastic/cloud-on-k8s/pull/7435)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
