### PR TITLE
[2.9] 2.9.0 release notes and highlights and Logstash volume docs (#7003)

### PR DESCRIPTION
**Pull request by pebrc**
# Backport

This will backport the following commits from `main` to `2.9`:
 - [2.9.0 release notes and highlights and Logstash volume docs (#7003)](https://github.com/elastic/cloud-on-k8s/pull/7003)

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

### CODE REVIEW

**Comment by pebrc** [comment]
@elasticmachine build elasticsearch-ci/docs

**Comment by pebrc** [comment]
@elasticmachine, run elasticsearch-ci-docs

**Comment by pebrc** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Review by thbkrkr — APPROVED** [review]

**Comment by pebrc** [comment]
I think we need #7025 before we can merge this

**Pull request merged**
