### PR TITLE
Release notes for 1.3.2

### PR DESCRIPTION
**Pull request by pebrc**
Combined highlights and release notes

### CODE REVIEW

**Review by charith-elastic — APPROVED** [review]

**Review by david-kow — APPROVED** [review]
LGTM

**Comment by pebrc** [comment]
@elasticmachine-ci run docs build

**Comment by pebrc** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by pebrc** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Pull request merged**
