### PR TITLE
Update service-meshes.asciidoc - correct k8 service name

### PR DESCRIPTION
**Pull request by deepakdeore2004**
k8 service name isn't correct, correct syntax is <svc-name>.<namespace>.svc.cluster.local

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/cloud-on-k8s/tree/master/CONTRIBUTING.md)?
- If you submit code, is your pull request against master? We recommend pull requests against master. We will backport them as needed.

### CODE REVIEW

**Comment by deepakdeore2004** [comment]
I just signed the contributor agreement

**Comment by barkbay** [comment]
cla/check

**Comment by barkbay** [comment]
cla/check

**Comment by barkbay** [comment]
jenkins test this please

**Pull request merged**
