### PR TITLE
Adjust machine type for ocp ci tests.

### PR DESCRIPTION
**Pull request by naemono**
From ocp tests: `0/6 nodes are available: 3 Insufficient memory`
Test: TestCustomHTTPCA

Do we want to try adjusting to 
```
-  machineType: n1-standard-8
+  machineType: n1-highmem-8
```

Which is `$0.548` vs `$0.44` and goes from 30GB to 52GB ram.

### CODE REVIEW

**Comment by naemono** [comment]
buildkite test this -f p=ocp -m s=8.16.0

**Comment by naemono** [comment]
Got a lot of 
```
        	            	expected status {Version:8.16.0 ExpectedNodes:1 AvailableNodes:1 Health: ObservedGeneration:0 ElasticsearchAssociationsStatus: MonitoringAssociationStatus: Selector:} but got {Version: ExpectedNodes:0 AvailableNodes:0 Health:red ObservedGeneration:0 ElasticsearchAssociationsStatus: MonitoringAssociationStatus: Selector:common.k8s.elastic.co/type=logstash,logstash.k8s.elastic.co/name=test-single-logstash-psgh}
```

But unsure why. Trying to replicate in local ocp cluster, but can't start pods:
```
15s         Warning   FailedCreatePodSandBox   pod/e2e-vif2w-operator-0         Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_e2e-vif2w-operator-0_e2e-vif2w-elastic-system_392022b2-dbcb-4abc-9ccd-b9a85291d0e5_0(07f5b293a2a4eddcda3b03b6ced4b20f07a14c403aa933e1087238e5146e6c6e): error adding pod e2e-vif2w-elastic-system_e2e-vif2w-operator-0 to CNI network "multus-cni-network": plugin type="multus-shim" name="multus-cni-network" failed (add): CmdAdd (shim): CNI request failed with status 400: 'ContainerID:"07f5b293a2a4eddcda3b03b6ced4b20f07a14c403aa933e1087238e5146e6c6e" Netns:"/var/run/netns/178863fd-826a-4921-8195-84763c2c00af" IfName:"eth0" Args:"IgnoreUnknown=1;K8S_POD_NAMESPACE=e2e-vif2w-elastic-system;K8S_POD_NAME=e2e-vif2w-operator-0;K8S_POD_INFRA_CONTAINER_ID=07f5b293a2a4eddcda3b03b6ced4b20f07a14c403aa933e1087238e5146e6c6e;K8S_POD_UID=392022b2-dbcb-4abc-9ccd-b9a85291d0e5" Path:"" ERRORED: error configuring pod [e2e-vif2w-elastic-system/e2e-vif2w-operator-0] networking: Multus: [e2e-vif2w-elastic-system/e2e-vif2w-operator-0/392022b2-dbcb-4abc-9ccd-b9a85291d0e5]: error waiting for pod: Unauthorized...
```

I'm sure it has to do with the SA that's being used... working through it...

**Comment by naemono** [comment]
`FailedCreatePodSandBox` turned out to be an issue within my cluster itself. The other issue seems to be that the pod never runs in ocp because of missing SCC. I'm testing adding that, but it makes me wonder how this ever worked at all in e2e tests.

**Comment by naemono** [comment]
buildkite test this -f p=ocp -m s=8.16.0

**Comment by barkbay** [comment]
>  it makes me wonder how this ever worked at all in e2e tests

Sorry, I broke them in https://github.com/elastic/cloud-on-k8s/pull/8348, I've been working on a fix in https://github.com/elastic/cloud-on-k8s/pull/8376

**Comment by naemono** [comment]
> > it makes me wonder how this ever worked at all in e2e tests
> 
> Sorry, I broke them in #8348, I've been working on a fix in #8376

Yeah, I noticed this yesterday. Sorry I missed that. I was working towards a similar resolution as you finished in #8376. Thanks!

**Pull request closed without merging**
