### PR TITLE
Elasticsearch: always set discovery.seed_hosts to empty array

### LINKED ISSUE #5834: Set discovery.seed_hosts: [] even when using file based seed hosts provider
It is recommended to set `discovery.seed_hosts: []` in `elasticsearch.yml` (static setting) even in the presence of the `discovery.seed_providers: file`. 

The setting has an effect even if the seed provider is file based and relies on `unicast_hosts.txt` as it is the case with ECK operator managed Elasticsearch clusters. 

If left unset and something goes wrong with the master we will get a bunch of noise about being unable to discover nodes at the default address(es) i.e. trying and failing to connect to at least `127.0.0.1:${TRANSPORT_PORT}` (paraphrasing @\DaveCTurner here)

### PR DESCRIPTION
**Pull request by pebrc**
Fixes #5834

### CODE REVIEW

**Review by thbkrkr — COMMENTED** [review]
Should we add the setting to https://www.elastic.co/guide/en/cloud-on-k8s/2.3/k8s-reserved-settings.html? By the way, `discovery.seed_providers` is missing.

**Comment by thbkrkr** [comment]
run/e2e-tests tags=es

**Comment by pebrc** [comment]
`discovery.seed_hosts` did not exist in 6.8 I need to add some version specific code.

**Review by thbkrkr — APPROVED** [review]
LGTM

**Comment by pebrc** [comment]
Jenkins test this please

**Pull request merged**
