### PR TITLE
Add script to call Buildkite API to trigger RedHat ECK release

### PR DESCRIPTION
**Pull request by thbkrkr**
This adds a script with the curl command to call the Buildkite API to trigger the pipeline `cloud-on-k8s-operator-redhat-release`that releases ECK for OperatoHub/RedHat. This also enables building branches for this pipeline.

Test:
```
BK_TOKEN=$(jq .graphql_token ~/.buildkite/config.json -r) USERNAME=thb \
  ECK_VERSION=v2.8.0-bc4 DRY_RUN=true ./trigger-bk-release.sh
```
https://buildkite.com/elastic/cloud-on-k8s-operator-redhat-release/builds/29

### CODE REVIEW

**Review by barkbay — APPROVED** [review]
Can't test it because of
`
{
  "message": "Branches have been disabled for this pipeline"
}
`
But LGTM 👍

**Comment by barkbay** [comment]
Does the error message mean that this should be "backported" to `2.8`?

**Comment by thbkrkr** [comment]
Yes this needs to be backported to `2.8.`.

**Comment by thbkrkr** [comment]
I withdraw what I said, no need for backport, only the [`catalog-info.yaml`](https://github.com/elastic/cloud-on-k8s/blob/main/catalog-info.yaml) present in `main` is used to configure the pipelines. A backport would be needed if we changed `.buildkite/pipeline-release-redhat.yml` https://github.com/elastic/cloud-on-k8s/blob/96f728ba49dddcc05fae474fc51ef911a20e7783/catalog-info.yaml#L108

**Comment by naemono** [comment]
Thanks @thbkrkr . I'll get a PR up to remove this from the operatorhub go binary for now

**Pull request merged**
