### PR TITLE
[ci/pipeline-gen] Lookup test env vars not current env

### PR DESCRIPTION
**Pull request by thbkrkr**
Looks for `BUILD_LICENSE_PUBKEY` in the env of the test to run (mixed and fixed env vars) instead of the current env to know if the operator needs to be suffixed.

This part will be revisited: https://github.com/elastic/cloud-on-k8s/issues/6567.

Fixes `TestElasticMapsServerCrossNSAssociation` in `8.7.0-SNAPSHOT`.

Relates to #6583.

### CODE REVIEW

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.7.0-SNAPSHOT,BUILD_LICENSE_PUBKEY=dev,TEST_LICENSE_PKEY_PATH=in-memory

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.7.0-SNAPSHOT,t=TestElasticMapsServerCrossNSAssociation,BUILD_LICENSE_PUBKEY=dev,TEST_LICENSE_PKEY_PATH=in-memory

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.7.0-SNAPSHOT,t=TestElasticMapsServerCrossNSAssociation,BUILD_LICENSE_PUBKEY=dev,TEST_LICENSE_PKEY_PATH=in-memory

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.7.0-SNAPSHOT,t=TestElasticMapsServerCrossNSAssociation,BUILD_LICENSE_PUBKEY=dev,TEST_LICENSE_PKEY_PATH=in-memory

**Comment by thbkrkr** [comment]
buildkite test this -f p=gke,s=8.7.0-SNAPSHOT,t=TestElasticMapsServerCrossNSAssociation,BUILD_LICENSE_PUBKEY=dev,TEST_LICENSE_PKEY_PATH=in-memory

**Review by pebrc — APPROVED** [review]

**Pull request merged**
