### PR TITLE
Fix job for running e2e test against different ELK stack versions

### PR DESCRIPTION
**Pull request by artemnikitin**
Job is currently failing https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-stack/ because of 
> However, thanks to this PR, I spotted that we accidentally added an accolade.

### CODE REVIEW

**Comment by thbkrkr** [comment]
This was done in #1836 
However, thanks to this PR, I spotted that we accidentally added an [accolade](https://github.com/elastic/cloud-on-k8s/blob/master/build/ci/e2e/stack_versions.jenkinsfile#L62).

**Comment by artemnikitin** [comment]
I think https://github.com/elastic/cloud-on-k8s/pull/1836 doesn't cover everything. We need to change also at least here: https://github.com/elastic/cloud-on-k8s/blob/master/Makefile#L325

**Comment by artemnikitin** [comment]
> However, thanks to this PR, I spotted that we accidentally added an accolade.

Fixed

**Comment by artemnikitin** [comment]
jenkins test this please

**Pull request merged**
