### PR TITLE
Workaround controller-runtime webhook upsert bug (#1337)

### PR DESCRIPTION
**Pull request by pebrc**
Backport of #1337

### CODE REVIEW

**Comment by pebrc** [comment]
Jenkins test this please

**Comment by pebrc** [comment]
Build keeps failing in build docs stage with 
```
16:18:38  Error executing: /node_modules/parcel/bin/cli.js build resources/web/docs_js/index.js /node_modules -d resources/web -o docs.js 
16:18:38  
16:18:38  ---
16:18:38  Can't exec "/node_modules/parcel/bin/cli.js": No such file or directory at lib/ES/Util.pm line 653.
16:18:39  Makefile:183: recipe for target 'ci-build-docs' failed
```

**Comment by artemnikitin** [comment]
@pebrc PR with fix https://github.com/elastic/cloud-on-k8s/pull/1351

**Comment by anyasabo** [comment]
Jenkins test this please

**Pull request merged**
