### PR TITLE
Support aks/ocp/tanzu e2e tests on Buildkite

### PR DESCRIPTION
**Pull request by thbkrkr**
This commit enables e2e-tests on the OCP, AKS and Tanzu k8s platforms.

They are run on a `gcp` agent due to the dependency on Docker of the ocp and tanzu deployer drivers to get the ocp installer and azr CLI respectively using a "client Docker image" .

Because the deployer run in Docker, the VAULT_TOKEN env variable needs to be propagated.

### CODE REVIEW

**Comment by thbkrkr** [comment]
Build [success](https://buildkite.com/elastic/cloud-on-k8s-operator/builds/820) from 2680043.

**Review by pebrc — APPROVED** [review]
LGTM I did not do any additional testing.

**Comment by thbkrkr** [comment]
Since the last review, I pushed d15e29d to fix an issue in the cleanup steps, then temporarily pushed d9a22ad to retest again. Builds failed due to `Quota 'STATIC_ADDRESSES' exceeded` which should be fixed now. Let's see.

**Comment by thbkrkr** [comment]
New failure when deleting a GKE cluster:
```
Deleted [https://container.googleapis.com/v1beta1/projects/elastic-cloud-dev/zones/europe-west6/clusters/eck-bk-e2e-gke-121-1080].
gke-eck-bk-e2e-gke-121-pvc-f809059f-6b77-4afc-9540-51243b3613f1,https://www.googleapis.com/compute/v1/projects/elastic-cloud-dev/zones/europe-west6-c
ERROR: (gcloud.compute.disks.delete) Could not fetch resource:
 - The disk resource 'projects/elastic-cloud-dev/zones/europe-west6-c/disks/gke-eck-bk-e2e-gke-121-pvc-f809059f-6b77-4afc-9540-51243b3613f1' is already being used by 'projects/elastic-cloud-dev/zones/europe-west6-c/instances/gke-eck-bk-e2e-gke-121-6-default-pool-4e73c991-dh9s'
```

And all OCP cluster creation failed. I don't know why without increasing the verbosity of the log.

**Comment by thbkrkr** [comment]
I missed two things with OCP: we test the latest version every day of the week and we test sequentially (not in parallel, mainly for quota reasons) all the versions supported on week-ends. As this is more involved than what is in this PR, I will only keep the run on the latest version in this PR and will continue with a follow up for testing of all versions.

**Comment by thbkrkr** [comment]
buildkite test this please

**Pull request merged**
