### PR TITLE
Update users-and-roles.asciidoc

### PR DESCRIPTION
**Pull request by matzegebbe**
somehow ${PWD} is displayed as YOUR PASSWORD in the documentation

```
-v ${PWD}/filerealm:/usr/share/elasticsearch/config
```
result:

image

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/cloud-on-k8s/tree/master/CONTRIBUTING.md)?
- If you submit code, is your pull request against master? We recommend pull requests against master. We will backport them as needed.

### CODE REVIEW

**Comment by sebgl** [comment]
Interesting! thanks for reporting @matzegebbe.

@alaudazzi do you know about something in our docs building process that would replace `${PWD}` by `$YOUR_PASSWORD`? In our case `${PWD}` is the linux variable, not a placeholder for a password variable.

**Comment by alaudazzi** [comment]
@sebgl in the generated output, ${PWD} is lower case and rendered as follows:

image

Is this the expected output?

**Comment by pebrc** [comment]
@sebgl I think this is due to a shared attribute here:

```
:pwd:             YOUR_PASSWORD
```

https://github.com/elastic/docs/blob/5a9f4b641ef7f5d1568718dc3120b799825f8206/shared/attributes.asciidoc#L298

**Comment by sebgl** [comment]
@pebrc thanks! That's unfortunate.
@alaudazzi sorry I meant in the currently published documentation, not in this PR.

@matzegebbe thanks again for noticing this. On my machine (TM), `${pwd}` does not render to anything (as opposed to `${PWD}` which prints the current path). I think `$(pwd)` (the actual command, not the variable) would work fine though. Would you mind changing it in that PR?
You also need to sign the [contributor agreement](https://www.elastic.co/contributor-agreement).

**Comment by sebgl** [comment]
🤦 very sorry @matzegebbe I just noticed your first commit had the correct `$(pwd)`, for some reasons I read it as `${pwd}`. Would you mind switching back to `$(pwd)`?

**Comment by matzegebbe** [comment]
@sebgl 
I hope I got you right. I changed $(pwd) to ${pwd}. But if someone want to "copy+paste" the docker run command it really has to be $(pwd) to make it work since ${pwd} will be empty. So the ${pwd} will only be a hint.

that was my first change but $pwd == ${PWD} on my system
image

**Comment by matzegebbe** [comment]
Ok, done.

**Comment by sebgl** [comment]
Jenkins test this please

**Comment by sebgl** [comment]
I'll merge this to 1.2 first (because git conflicts!), then open a similar PR for master and 1.1.

**Pull request merged**
