### PR TITLE
Fix EnterpriseSearch upgrade with TLS disabled

### LINKED ISSUE #6185: Reconciliation error upgrading enterprise search with TLS disabled
## Bug Report
**What did you do?**
I'm trying to upgrade enterprise search from 8.3.3 to 8.4.3 using the ECK operator. The cluster runs fine with version 8.3.3, but the operator refuses to upgrade complaining about a missing secret. The cluster has TLS disabled, using this guide: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-service-mesh-istio.html

**What did you expect to see?**
An upgraded enterprise search deployment.

**What did you see instead? Under which circumstances?**

The controller errors out with a 'Reconciliation failure', see the logs below.
I suspect this is because I have disabled TLS for both elasticsearch and enterprise search in favor of a cluster-wide istio installation.

**Environment**

* ECK version: 2.5.0

* Kubernetes information:

We use GKE, version 1.23.

```
$ kubectl version --short
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.23.12-gke.100
```

* Resource definition:

The appsearch cluster:
```
apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: ens
  namespace: elastic
spec:
  config:
    elasticsearch.ssl.enabled: false
    ent_search.external_url: https://ens.<something>
    kibana.external_url: https://kibana.<something>
    kibana.host: http://kibana-kb-http:5601
  count: 2
  elasticsearchRef:
    name: my-elastic
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 8.4.3
```

And the elasticsearch cluster:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: my-elastic
  namespace: elastic
spec:
  http:
    tls:
      certificate: {}
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - count: 2
    name: default
    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/includeInboundPorts: '*'
  transport:
    tls:
      certificate: {}
  version: 8.4.3
```

* Logs:
```
{"log.level":"info","@timestamp":"2022-11-21T07:56:36.123Z","log.logger":"enterprisesearch-controller","message":"Starting reconciliation run","service.version":"2.5.0+642f9ecd","service.type":"eck","ecs.version":"1.4.0","iteration":"37","namespace":"elastic","ent_name":"ens"}
{"log.level":"info","@timestamp":"2022-11-21T07:56:36.124Z","log.logger":"enterprisesearch-controller","message":"Enabling read-only mode for version upgrade","service.version":"2.5.0+642f9ecd","service.type":"eck","ecs.version":"1.4.0","iteration":"37","namespace":"elastic","ent_name":"ens","namespace":"elastic","ent_name":"ens","target_version":"8.4.3"}
{"log.level":"info","@timestamp":"2022-11-21T07:56:36.124Z","log.logger":"enterprisesearch-controller","message":"Ending reconciliation run","service.version":"2.5.0+642f9ecd","service.type":"eck","ecs.version":"1.4.0","iteration":"37","namespace":"elastic","ent_name":"ens","took":0.000714316}
{"log.level":"error","@timestamp":"2022-11-21T07:56:36.124Z","log.logger":"manager.eck-operator","message":"Reconciler error","service.version":"2.5.0+642f9ecd","service.type":"eck","ecs.version":"1.4.0","controller":"enterprisesearch-controller","object":{"name":"ens","namespace":"elastic"},"namespace":"elastic","name":"ens","reconcileID":"dd2c8f1d-d3da-46c9-b20f-a66ef1743ebf","error":"version upgrade: Secret \"ens-ent-http-certs-internal\" not found","errorCauses":[{"error":"version upgrade: Secret \"ens-ent-http-certs-internal\" not found"}],"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
```

### PR DESCRIPTION
**Pull request by thbkrkr**
Correctly create the HTTP client to call the EnterpriseSearch API when TLS is disabled at the EnterpriseSearch resource level.

Resolves #6185.

Since the HTTP client is mocked in the unit test, I didn't update it. If we want to cover this with a test, one option would be to extract the client creation in another method and test that one. It didn't seem worth it to me.

I made a pass on the places where `apmhttp.WrapClient`and `commonhttp.Client` are called and I did not find any other occurrence of this bug.

### CODE REVIEW

**Review by pebrc — APPROVED** [review]
LGTM the only thing I am not happy with is that we never test this scenario. But I admit that setting up a service mesh based test would be separate task. So let's fix the bug first.

**Comment by thbkrkr** [comment]
I'm not satisfied either. We could update `TestEnterpriseSearchVersionUpgradeToLatest8x` to also test the upgrade of ent without TLS. This way, we don't add a new e2e test just for this and we don't make the existing longer either.

```diff
diff --git a/test/e2e/ent/ent_test.go b/test/e2e/ent/ent_test.go
index f70144451..1feccc4db 100644
--- a/test/e2e/ent/ent_test.go
+++ b/test/e2e/ent/ent_test.go
@@ -89,11 +89,19 @@ func TestEnterpriseSearchVersionUpgradeToLatest8x(t *testing.T) {
                WithVersion(srcVersion).
                WithRestrictedSecurityContext()
 
+       entNoTLS := enterprisesearch.NewBuilder(name).
+               WithElasticsearchRef(es.Ref()).
+               WithNodeCount(1).
+               WithVersion(srcVersion).
+               WithTLSDisabled(true).
+               WithRestrictedSecurityContext()
+
        esUpgraded := es.WithVersion(dstVersion).WithMutatedFrom(&es)
        entUpgraded := ent.WithVersion(dstVersion).WithMutatedFrom(&ent)
+       entNoTLSUpgraded := entNoTLS.WithVersion(dstVersion).WithMutatedFrom(&entNoTLS)
 
        // During the version upgrade, the operator will toggle Enterprise Search read-only mode.
        // We don't verify this behaviour here. Instead, we just check Enterprise Search eventually
        // runs fine in the new version: it would fail to run if read-only mode wasn't toggled.
-       test.RunMutations(t, []test.Builder{es, ent}, []test.Builder{esUpgraded, entUpgraded})
+       test.RunMutations(t, []test.Builder{es, ent, entNoTLS}, []test.Builder{esUpgraded, entUpgraded, entNoTLSUpgraded})
```

**Comment by thbkrkr** [comment]
My proposal doesn't work. It seems that one Elasticsearch shared between two different Enterprise Search makes problem. The test runner received 401 error when reaching the API of the second enterpriseSearch using the API key auth method.

**Comment by thbkrkr** [comment]
I opted to turn `TestEnterpriseSearchTLSDisabled` into `TestEnterpriseSearchTLSDisabledVersionUpgradeToLatest8x`.

**Comment by thbkrkr** [comment]
run/e2e-tests match=TestEnterpriseSearchTLSDisabledVersionUpgradeToLatest8x

**Pull request merged**
