### PR TITLE
Stop using deprecated xpack.fleet.agents.elasticsearch.host Kibana config

### PR DESCRIPTION
**Pull request by david-kow**
Fixes https://github.com/elastic/cloud-on-k8s/issues/5091.

### CODE REVIEW

**Comment by david-kow** [comment]
run full pr build

**Comment by david-kow** [comment]
run full pr build

**Comment by david-kow** [comment]
run full pr build

**Comment by david-kow** [comment]
run full pr build

**Comment by david-kow** [comment]
run full pr build

EMS license issue (?) - rerunning.

**Comment by barkbay** [comment]
> EMS license issue (?) - rerunning.

Might be related to https://github.com/elastic/cloud-on-k8s/issues/5231

**Comment by david-kow** [comment]
run full pr build

**Review by pebrc — APPROVED** [review]

**Pull request merged**
