### PR TITLE
Generate xUnit XML with test results in the case of test fail

### PR DESCRIPTION
**Pull request by artemnikitin**
Original PR https://github.com/elastic/cloud-on-k8s/pull/1724 added generation of xUnit compatible XML for unit and integration but misses a bug. In the case if tests failed XML will not be generated. This PR fixes that

### CODE REVIEW

**Comment by charith-elastic** [comment]
There's some duplicated effort with #1806 :smile: 

Any reason why we can't directly use `gotestsum` as I have done in #1806? I feel like it would be simpler to understand.

**Comment by artemnikitin** [comment]
@charith-elastic Good catch, thanks. I will fix that.

**Comment by artemnikitin** [comment]
First failed integration test handled by generated XML 😃 
https://devops-ci.elastic.co/job/cloud-on-k8s-pr/1496/testReport/junit/github/com_elastic_cloud-on-k8s_pkg_controller_license/TestReconcile/

**Comment by artemnikitin** [comment]
jenkins test this please

**Comment by artemnikitin** [comment]
jenkins test this please

**Comment by artemnikitin** [comment]
jenkins test this please

**Pull request merged**
