### PR TITLE
Remove pointer utils package in favor of k8s.io/utils

### PR DESCRIPTION
**Pull request by racevedoo**
This PR removes utility functions used for building pointer values for `int32` and `int64` in favor of using `k8s.io/utils`.

### CODE REVIEW

**Comment by thbkrkr** [comment]
jenkins test this please

**Comment by thbkrkr** [comment]
CI fails with:
```
14:06:08  make --no-print-directory generate-notice-file
14:06:08  go: downloading github.com/karrick/godirwalk v1.10.12
14:06:08  go: extracting github.com/karrick/godirwalk v1.10.12
14:06:08  go: finding github.com/karrick/godirwalk v1.10.12
14:06:09  github.com/karrick/godirwalk
14:06:09  github.com/elastic/cloud-on-k8s/hack/licence-detector/detector
14:06:09  github.com/elastic/cloud-on-k8s/hack/licence-detector
14:06:10  
14:06:10  Error: dirty local changes
14:06:10   M NOTICE.txt
14:06:10  Makefile:419: recipe for target 'check-local-changes' failed
```

The new `k8s.io/utils` direct dependency involves regenerating the notice file. 
@racevedoo Can you update the `NOTICE.txt` file using `make generate-notice-file`?

**Comment by sebgl** [comment]
Now that I look at it I'm wondering whether this is the right move. It ties us to directly a particular version of `k8s.io` modules only so we can reuse one small function.
(Sorry @racevedoo I know we discussed going into that direction in another PR).

Curious about other folks thoughts on this.

**Comment by sebgl** [comment]
I discussed it with @pebrc, we think it's probably not worth adding the extra direct dependency to `k8s.io/util` for a small util function like this one.
Sorry for leading you into that direction @racevedoo I hope you understand the decision! Still thanks for your contribution :)

**Pull request closed without merging**
