### PR TITLE
feat(helm/operator): statefulset labels and annotations

### PR DESCRIPTION
**Pull request by nromriell**
Updates eck-operator helm chart to support annotations and labels on the statefulset for the operator. This is useful for telemetry and tracking.

Adds two new keys to values
`statefulsetAnnotations` -- defines the annotations that should be added to the operator StatefulSet
`statefulsetLabels` -- defines additional labels that should be added to the operator StatefulSet

And then updates deploy/eck-operator/templates/statefulset.yaml to support these new values

### CODE REVIEW

**Review by thbkrkr — APPROVED** [review]
LGTM

**Comment by thbkrkr** [comment]
buildkite test this

**Comment by thbkrkr** [comment]
Thank you Nathan!

**Comment by nromriell** [comment]
Thanks @thbkrkr!

**Pull request merged**
